
---------------------------------------INDICADOR 1------------------------------------------------------------------------------------------------------------------------------

SELECT ORDEN,ADUANA,REGIMEN,AÑO,TIPO_DESPACHO_ORDEN,fec_usua_crea,FEC_DOC_COMPLETA,FEC_DESPACHO,horario_despacho,NOMBRE_TERMINAL,TIPO_DIRECCIONAMIENTO,
--ADU118_REGI10,APM_DPW,

F_INDICADOR1_OPERA(ADUANA,REGIMEN,COD_TERMINAL,NOMBRE_TERMINAL,TIPO_DIRECCIONAMIENTO,FEC_DOC_COMPLETA,FEC_DESPACHO) INDICADOR

FROM
    (SELECT O.NUME_ORDEN ORDEN,O.CODI_ADUAN ADUANA,O.CODI_REGI REGIMEN,
    DECODE(O.CODI_TDESP,'1-0','Anticipado','0-0','Excepcional','0-1','Urgente','') TIPO_DESPACHO_ORDEN,
    (SELECT DESCRIPCION FROM TIPO_ANTICIPADO WHERE ADUANA = O.CODI_ADUAN AND CODIGO = O.tipo_despacho) AS t_despacho,
    O.ANO_PRESE AÑO,O.CLIENTE,O.CODI_CLIE,A.fec_usua_crea,A.fec_despacho,
    (SELECT DES_HORARIO FROM HORARIO WHERE COD_HORARIO = A.hor_prog)horario_despacho,
    O.FEC_RETIRO,A.doc_completa,A.fec_doc_completa,
    (SELECT RAZ_SOCIAL FROM ALMAC_ADUANA A WHERE A.COD_ALMAC = O.COD_TERMINAL) NOMBRE_TERMINAL,
    (SELECT TIPO_DIRECCIONAMIENTO FROM SOLICITUD_VB LEFT JOIN solicitud_vb_orden S ON (S.ANIO_SOLICITUD=SOLICITUD_VB.ANIO_SOLICITUD AND S.nro_solicitud = SOLICITUD_VB.NRO_SOLICITUD AND S.ORDEN_MADRE = 1) WHERE 
    (SOLICITUD_VB.EMPRESA = '001') AND (s.ANO_PRESE = A.ANO_PRESE ) AND (s.NUME_ORDEN = O.NUME_ORDEN ) AND ROWNUM=1) TIPO_DIRECCIONAMIENTO,
    --CASE WHEN O.CODI_ADUAN = '118' AND O.CODI_REGI = '10' THEN 'SI' ELSE 'NO' END ADU118_REGI10,
    --CASE WHEN O.COD_TERMINAL IN ('4004','3014') THEN 'SI' ELSE 'NO' END APM_DPW
    FROM ORDEN O 
    INNER JOIN prog_despacho_cab A ON (O.EMPRESA = A.EMPRESA AND O.NUME_ORDEN = A.NUME_ORDEN AND O.CODI_REGI = A.CODI_REGI AND O.CODI_ADUAN = A.CODI_ADUAN AND O.ANO_PRESE = A.ANO_PRESE)
    WHERE 
    (F_ORDEN_PARCIAL(O.CODI_ADUAN,O.CODI_REGI,O.ANO_PRESE,O.NUME_ORDEN) = 0) 
    AND O.CODI_ADUAN NOT IN ('40','60','50','52')
    AND TRUNC(O.FEC_RETIRO) BETWEEN ADD_MONTHS(TRUNC(SYSDATE,'MM'),-4) AND LAST_DAY(TRUNC(SYSDATE))
    --AND TRUNC(O.FEC_RETIRO) BETWEEN  TO_DATE('01/12/2022','dd/mm/yyyy') AND TO_DATE('31/12/2022','dd/mm/yyyy'))
--ORDER BY ORDEN ASC

----------NEW---------------------

SELECT ORDEN,ADUANA,REGIMEN,AÑO,CLIENTE,TIPO_DESPACHO_ORDEN,T_DESPACHO,fec_usua_crea,FEC_DOC_COMPLETA,TO_char(FEC_DESPACHO,'dd/mm/yyyy') FECHA_DESPACHO,HORARIO_DESPACHO,FEC_RETIRO,NOMBRE_TERMINAL,DIRECCIONAMIENTO,

F_INDICADOR1_OPERA(ADUANA,REGIMEN,COD_TERMINAL,NOMBRE_TERMINAL,DIRECCIONAMIENTO,FEC_DOC_COMPLETA,FEC_DESPACHO) INDICADOR
FROM
    (SELECT O.NUME_ORDEN ORDEN,O.CODI_ADUAN ADUANA,O.CODI_REGI REGIMEN,
    DECODE(O.CODI_TDESP,'1-0','Anticipado','0-0','Excepcional','0-1','Urgente','') TIPO_DESPACHO_ORDEN,
    (SELECT DESCRIPCION FROM TIPO_ANTICIPADO WHERE ADUANA = O.CODI_ADUAN AND CODIGO = O.tipo_despacho) AS T_DESPACHO,
    (SELECT RASON_SOCIAL from CLIENTES where CODIGOANT = O.CODI_CLIE AND ROWNUM=1) CLIENTE,
    O.ANO_PRESE AÑO,A.fec_usua_crea,A.fec_despacho,O.COD_TERMINAL,
    (SELECT DES_HORARIO FROM HORARIO WHERE COD_HORARIO = A.hor_prog)horario_despacho,
    O.FEC_RETIRO,A.doc_completa,A.fec_doc_completa,
    (SELECT RAZ_SOCIAL FROM ALMAC_ADUANA A WHERE A.COD_ALMAC = O.COD_TERMINAL) NOMBRE_TERMINAL,
    (SELECT TIPO_DIRECCIONAMIENTO FROM SOLICITUD_VB LEFT JOIN solicitud_vb_orden S ON (S.ANIO_SOLICITUD=SOLICITUD_VB.ANIO_SOLICITUD AND S.nro_solicitud = SOLICITUD_VB.NRO_SOLICITUD AND S.ORDEN_MADRE = 1) WHERE 
    (SOLICITUD_VB.EMPRESA = '001') AND (s.ANO_PRESE = A.ANO_PRESE ) AND (s.NUME_ORDEN = O.NUME_ORDEN ) AND ROWNUM=1) DIRECCIONAMIENTO
    FROM ORDEN O 
    INNER JOIN prog_despacho_cab A ON (O.EMPRESA = A.EMPRESA AND O.NUME_ORDEN = A.NUME_ORDEN AND O.CODI_REGI = A.CODI_REGI AND O.CODI_ADUAN = A.CODI_ADUAN AND O.ANO_PRESE = A.ANO_PRESE)
    WHERE 
    (F_ORDEN_PARCIAL(O.CODI_ADUAN,O.CODI_REGI,O.ANO_PRESE,O.NUME_ORDEN) = 0) 
    AND O.CODI_ADUAN ='118'
    AND O.CODI_REGI = '10'
    AND O.COD_TERMINAL IN ('3014','4004')
    AND TRUNC(O.FEC_RETIRO) BETWEEN ADD_MONTHS(TRUNC(SYSDATE,'MM'),-4) AND LAST_DAY(TRUNC(SYSDATE)))
    WHERE DIRECCIONAMIENTO = 'DD'


---------------------------------------INDICADOR 2------------------------------------------------------------------------------------------------------------------------------

SELECT ORDEN,ADUANA,REGIMEN,AÑO,TIPO_DESPACHO_ORDEN,FEC_DOC_COMPLETA,((TRUNC(FEC_DESPACHO)-1) +18/24) DIA_6PM_FEC_DESPACHO,FEC_DESPACHO,COD_TERMINAL,NOMBRE_TERMINAL,TIPO_DIRECCIONAMIENTO,ADU118_R107030,APM_DPW,

F_INDICADOR2_OPERA(ADUANA,REGIMEN,COD_TERMINAL,TIPO_DIRECCIONAMIENTO,FEC_DOC_COMPLETA,FEC_DESPACHO) INDICADOR

FROM
    (SELECT O.NUME_ORDEN ORDEN,O.CODI_ADUAN ADUANA,O.CODI_REGI REGIMEN,
    DECODE(O.CODI_TDESP,'1-0','Anticipado','0-0','Excepcional','0-1','Urgente','') TIPO_DESPACHO_ORDEN,
    (SELECT DESCRIPCION FROM TIPO_ANTICIPADO WHERE ADUANA = O.CODI_ADUAN AND CODIGO = O.tipo_despacho) AS t_despacho,
    O.ANO_PRESE AÑO,O.CLIENTE,O.CODI_CLIE,A.fec_usua_crea,A.fec_despacho,
    (SELECT DES_HORARIO FROM HORARIO WHERE COD_HORARIO = A.hor_prog)horario_despacho,
    O.FEC_RETIRO,A.doc_completa,A.fec_doc_completa,O.COD_TERMINAL,
    (SELECT RAZ_SOCIAL FROM ALMAC_ADUANA A WHERE A.COD_ALMAC = O.COD_TERMINAL) NOMBRE_TERMINAL,
    (SELECT TIPO_DIRECCIONAMIENTO FROM SOLICITUD_VB LEFT JOIN solicitud_vb_orden S ON (S.ANIO_SOLICITUD=SOLICITUD_VB.ANIO_SOLICITUD AND S.nro_solicitud = SOLICITUD_VB.NRO_SOLICITUD AND S.ORDEN_MADRE = 1) WHERE 
    (SOLICITUD_VB.EMPRESA = '001') AND (s.ANO_PRESE = A.ANO_PRESE ) AND (s.NUME_ORDEN = O.NUME_ORDEN ) AND ROWNUM=1) TIPO_DIRECCIONAMIENTO,
    CASE WHEN O.CODI_ADUAN = '118' AND O.CODI_REGI IN ('10','70','30') THEN 'SI' ELSE 'NO' END ADU118_R107030,
    CASE WHEN O.COD_TERMINAL IN ('4004','3014') THEN 'SI' ELSE 'NO' END APM_DPW
    FROM ORDEN O 
    INNER JOIN prog_despacho_cab A ON (O.EMPRESA = A.EMPRESA AND O.NUME_ORDEN = A.NUME_ORDEN AND O.CODI_REGI = A.CODI_REGI AND O.CODI_ADUAN = A.CODI_ADUAN AND O.ANO_PRESE = A.ANO_PRESE)
    WHERE 
    (F_ORDEN_PARCIAL(O.CODI_ADUAN,O.CODI_REGI,O.ANO_PRESE,O.NUME_ORDEN) = 0) 
    AND O.CODI_ADUAN NOT IN ('40','60','50','52')
    AND TRUNC(O.FEC_RETIRO) BETWEEN  TO_DATE('01/12/2022','dd/mm/yyyy') AND TO_DATE('31/12/2022','dd/mm/yyyy'))  

    -------------NEW---------------

    SELECT ORDEN,ADUANA,REGIMEN,AÑO,CLIENTE,TIPO_DESPACHO_ORDEN,T_DESPACHO,fec_usua_crea,FEC_DOC_COMPLETA,TO_char(FEC_DESPACHO,'dd/mm/yyyy') FECHA_DESPACHO,HORARIO_DESPACHO,FEC_RETIRO,NOMBRE_TERMINAL,DIRECCIONAMIENTO,

F_INDICADOR2_OPERA(ADUANA,REGIMEN,COD_TERMINAL,DIRECCIONAMIENTO,FEC_DOC_COMPLETA,FEC_DESPACHO) INDICADOR

FROM
    (SELECT O.NUME_ORDEN ORDEN,O.CODI_ADUAN ADUANA,O.CODI_REGI REGIMEN,
    DECODE(O.CODI_TDESP,'1-0','Anticipado','0-0','Excepcional','0-1','Urgente','') TIPO_DESPACHO_ORDEN,
    (SELECT DESCRIPCION FROM TIPO_ANTICIPADO WHERE ADUANA = O.CODI_ADUAN AND CODIGO = O.tipo_despacho) AS t_despacho,
    (SELECT RASON_SOCIAL from CLIENTES where CODIGOANT = O.CODI_CLIE AND ROWNUM=1) CLIENTE,
    O.ANO_PRESE AÑO,A.fec_usua_crea,A.fec_despacho,
    (SELECT DES_HORARIO FROM HORARIO WHERE COD_HORARIO = A.hor_prog)horario_despacho,
    O.FEC_RETIRO,A.doc_completa,A.fec_doc_completa,O.COD_TERMINAL,
    (SELECT RAZ_SOCIAL FROM ALMAC_ADUANA A WHERE A.COD_ALMAC = O.COD_TERMINAL) NOMBRE_TERMINAL,
    (SELECT TIPO_DIRECCIONAMIENTO FROM SOLICITUD_VB LEFT JOIN solicitud_vb_orden S ON (S.ANIO_SOLICITUD=SOLICITUD_VB.ANIO_SOLICITUD AND S.nro_solicitud = SOLICITUD_VB.NRO_SOLICITUD AND S.ORDEN_MADRE = 1) WHERE 
    (SOLICITUD_VB.EMPRESA = '001') AND (s.ANO_PRESE = A.ANO_PRESE ) AND (s.NUME_ORDEN = O.NUME_ORDEN ) AND ROWNUM=1) DIRECCIONAMIENTO
    FROM ORDEN O 
    INNER JOIN prog_despacho_cab A ON (O.EMPRESA = A.EMPRESA AND O.NUME_ORDEN = A.NUME_ORDEN AND O.CODI_REGI = A.CODI_REGI AND O.CODI_ADUAN = A.CODI_ADUAN AND O.ANO_PRESE = A.ANO_PRESE)
    WHERE 
    (F_ORDEN_PARCIAL(O.CODI_ADUAN,O.CODI_REGI,O.ANO_PRESE,O.NUME_ORDEN) = 0) 
    AND O.CODI_ADUAN = '118'
    AND O.COD_TERMINAL IN ('4004','3014')
    AND O.CODI_REGI IN ('10','70','30')
    AND TRUNC(O.FEC_RETIRO) BETWEEN ADD_MONTHS(TRUNC(SYSDATE,'MM'),-4) AND LAST_DAY(TRUNC(SYSDATE))) 
    WHERE DIRECCIONAMIENTO = '3B'

    ---------------------------------------INDICADOR 3------------------------------------------------------------------------------------------------------------------------------

SELECT ORDEN,ADUANA,REGIMEN,AÑO,TIPO_DESPACHO_ORDEN,FEC_DOC_COMPLETA,FEC_DESPACHO,HORARIO_DESPACHO,COD_TERMINAL,NOMBRE_TERMINAL,TIPO_DIRECCIONAMIENTO,ADU235,

F_INDICADOR3_OPERA(ADUANA,FEC_DOC_COMPLETA,FEC_DESPACHO,HORARIO_DESPACHO) INDICADOR

FROM
    (SELECT O.NUME_ORDEN ORDEN,O.CODI_ADUAN ADUANA,O.CODI_REGI REGIMEN,
    DECODE(O.CODI_TDESP,'1-0','Anticipado','0-0','Excepcional','0-1','Urgente','') TIPO_DESPACHO_ORDEN,
    (SELECT DESCRIPCION FROM TIPO_ANTICIPADO WHERE ADUANA = O.CODI_ADUAN AND CODIGO = O.tipo_despacho) AS t_despacho,
    O.ANO_PRESE AÑO,O.CLIENTE,O.CODI_CLIE,A.fec_usua_crea,A.fec_despacho,
    (SELECT DES_HORARIO FROM HORARIO WHERE COD_HORARIO = A.hor_prog)horario_despacho,
    O.FEC_RETIRO,A.doc_completa,A.fec_doc_completa,O.COD_TERMINAL,
    (SELECT RAZ_SOCIAL FROM ALMAC_ADUANA A WHERE A.COD_ALMAC = O.COD_TERMINAL) NOMBRE_TERMINAL,
    (SELECT TIPO_DIRECCIONAMIENTO FROM SOLICITUD_VB LEFT JOIN solicitud_vb_orden S ON (S.ANIO_SOLICITUD=SOLICITUD_VB.ANIO_SOLICITUD AND S.nro_solicitud = SOLICITUD_VB.NRO_SOLICITUD AND S.ORDEN_MADRE = 1) WHERE 
    (SOLICITUD_VB.EMPRESA = '001') AND (s.ANO_PRESE = A.ANO_PRESE ) AND (s.NUME_ORDEN = O.NUME_ORDEN ) AND ROWNUM=1) TIPO_DIRECCIONAMIENTO,
    CASE WHEN O.CODI_ADUAN = '235' THEN 'SI' ELSE 'NO' END ADU235
    FROM ORDEN O 
    INNER JOIN prog_despacho_cab A ON (O.EMPRESA = A.EMPRESA AND O.NUME_ORDEN = A.NUME_ORDEN AND O.CODI_REGI = A.CODI_REGI AND O.CODI_ADUAN = A.CODI_ADUAN AND O.ANO_PRESE = A.ANO_PRESE)
    WHERE 
    (F_ORDEN_PARCIAL(O.CODI_ADUAN,O.CODI_REGI,O.ANO_PRESE,O.NUME_ORDEN) = 0) 
    AND O.CODI_ADUAN NOT IN ('40','60','50','52')
    AND TRUNC(O.FEC_RETIRO) BETWEEN  TO_DATE('01/12/2022','dd/mm/yyyy') AND TO_DATE('31/12/2022','dd/mm/yyyy'))  
---------------NEW-----------------

SELECT ORDEN,ADUANA,REGIMEN,AÑO,CLIENTE,TIPO_DESPACHO_ORDEN,T_DESPACHO,fec_usua_crea,FEC_DOC_COMPLETA,TO_char(FEC_DESPACHO,'dd/mm/yyyy') FECHA_DESPACHO,HORARIO_DESPACHO,FEC_RETIRO,NOMBRE_TERMINAL,DIRECCIONAMIENTO,

F_INDICADOR3_OPERA(ADUANA,FEC_DOC_COMPLETA,FEC_DESPACHO,HORARIO_DESPACHO) INDICADOR

FROM
    (SELECT O.NUME_ORDEN ORDEN,O.CODI_ADUAN ADUANA,O.CODI_REGI REGIMEN,
    DECODE(O.CODI_TDESP,'1-0','Anticipado','0-0','Excepcional','0-1','Urgente','') TIPO_DESPACHO_ORDEN,
    (SELECT DESCRIPCION FROM TIPO_ANTICIPADO WHERE ADUANA = O.CODI_ADUAN AND CODIGO = O.tipo_despacho) AS t_despacho,
    (SELECT RASON_SOCIAL from CLIENTES where CODIGOANT = O.CODI_CLIE AND ROWNUM=1) CLIENTE,
    O.ANO_PRESE AÑO,A.fec_usua_crea,A.fec_despacho,
    (SELECT DES_HORARIO FROM HORARIO WHERE COD_HORARIO = A.hor_prog)horario_despacho,
    O.FEC_RETIRO,A.doc_completa,A.fec_doc_completa,O.COD_TERMINAL,
    (SELECT RAZ_SOCIAL FROM ALMAC_ADUANA A WHERE A.COD_ALMAC = O.COD_TERMINAL) NOMBRE_TERMINAL,
    (SELECT TIPO_DIRECCIONAMIENTO FROM SOLICITUD_VB LEFT JOIN solicitud_vb_orden S ON (S.ANIO_SOLICITUD=SOLICITUD_VB.ANIO_SOLICITUD AND S.nro_solicitud = SOLICITUD_VB.NRO_SOLICITUD AND S.ORDEN_MADRE = 1) WHERE 
    (SOLICITUD_VB.EMPRESA = '001') AND (s.ANO_PRESE = A.ANO_PRESE ) AND (s.NUME_ORDEN = O.NUME_ORDEN ) AND ROWNUM=1) DIRECCIONAMIENTO
    FROM ORDEN O 
    INNER JOIN prog_despacho_cab A ON (O.EMPRESA = A.EMPRESA AND O.NUME_ORDEN = A.NUME_ORDEN AND O.CODI_REGI = A.CODI_REGI AND O.CODI_ADUAN = A.CODI_ADUAN AND O.ANO_PRESE = A.ANO_PRESE)
    WHERE 
    (F_ORDEN_PARCIAL(O.CODI_ADUAN,O.CODI_REGI,O.ANO_PRESE,O.NUME_ORDEN) = 0) 
    AND O.CODI_ADUAN = '235'
    AND TRUNC(O.FEC_RETIRO) BETWEEN ADD_MONTHS(TRUNC(SYSDATE,'MM'),-4) AND LAST_DAY(TRUNC(SYSDATE)))

    ---------------------------------------------------------

    SELECT 
--RUC_PROVEEDOR,razon_social,ruc_adquirente,razon_social_adquirente,--decode(TIPO_DOCUMENTO,'01','FACTURA','07','NOTA CREDITO','08','NOTA DEBITO','NO ESPECIFICADO')TIPO_DOCUMENTO,
serie || '-'|| numero_documento nro_doc,
--fecha_emision,
--TRUNC(MOD(((TRUNC(fecha_registro)+18/24) - fecha_registro) * 24, 24)) HORA_1,
fecha_registro AS FECHA_SUBIDA_FACTURA,TO_CHAR(fecha_registro,'DAY') AS DIA_SUBIDA_FACTURA,
--codi_aduan ||'-'|| ano_prese ||'-'|| trim(codi_regi) ||'-'|| nume_orden ORDEN_VINCULADA,
--TRUNC(MOD(((TRUNC(f_cargar_orden)+18/24) - f_cargar_orden) * 24, 24)) HORA_2,
f_cargar_orden AS FECHA_VINCULO_ORDEN,
TO_CHAR(f_cargar_orden,'DAY') AS DIA_VINCULO_ORDEN,
--usuario_cargar_orden AS USUARIO_VINCULO_ORDEN,
DECODE(version_ubl,'2.1','AUTOMATICO','MANUAL') FORMA_SUBIDA_FACTURA,
--F_INDICADOR4_OPERA(fecha_registro,f_cargar_orden) INDICADOR4,
--F_DIA_FERIADO(fecha_registro) FERIADO,
F_FERIADOS(fecha_registro,f_cargar_orden) FERIADOS,
--ROUND(f_cargar_orden - fecha_registro,2) RESTA,
--F_INDICADOR4_OPERA(fecha_registro,f_cargar_orden) RESTA_LABORAL,
TRUNC(f_cargar_orden - fecha_registro) DIAS,
TRUNC(MOD((f_cargar_orden - fecha_registro) * 24, 24)) HORAS,
--TRUNC(MOD((f_cargar_orden - fecha_registro) * (60 * 24), 60)) MINUTOS,
--TRUNC(MOD((f_cargar_orden - fecha_registro) * (60 * 60 * 24), 60)) SEGUNDOS,
F_DIAS_HABILES_JMV(fecha_registro,f_cargar_orden) DIAS_HABILES,
CASE WHEN F_INDICADOR4_OPERA(fecha_registro,f_cargar_orden) = 0 THEN 'NO CUMPLE' ELSE 'SI CUMPLE' END INDICADOR
FROM FACE_FACTURAMZ
WHERE FECHA_EMISION BETWEEN ('01/12/2022') AND ('31/12/2022') AND
TIPO_DOCUMENTO='01' 
AND RUC_PROVEEDOR NOT IN ('20100246768','20100457629') 
AND dar_baja_flag IS NULL AND nume_orden IS NOT NULL
ORDER BY DIAS DESC


----------------------------NEW--------------------------------------------


SELECT 
--RUC_PROVEEDOR,razon_social,ruc_adquirente,razon_social_adquirente,--decode(TIPO_DOCUMENTO,'01','FACTURA','07','NOTA CREDITO','08','NOTA DEBITO','NO ESPECIFICADO')TIPO_DOCUMENTO,
serie || '-'|| numero_documento nro_doc,
--fecha_emision,
--TRUNC(MOD(((TRUNC(fecha_registro)+18/24) - fecha_registro) * 24, 24)) HORA_1,
fecha_registro AS FECHA_SUBIDA_FACTURA,TO_CHAR(fecha_registro,'DAY') AS DIA_SUBIDA_FACTURA,
--codi_aduan ||'-'|| ano_prese ||'-'|| trim(codi_regi) ||'-'|| nume_orden ORDEN_VINCULADA,
--TRUNC(MOD(((TRUNC(f_cargar_orden)+18/24) - f_cargar_orden) * 24, 24)) HORA_2,
f_cargar_orden AS FECHA_VINCULO_ORDEN,
TO_CHAR(f_cargar_orden,'DAY') AS DIA_VINCULO_ORDEN,
--usuario_cargar_orden AS USUARIO_VINCULO_ORDEN,
DECODE(version_ubl,'2.1','AUTOMATICO','MANUAL') FORMA_SUBIDA_FACTURA,
--F_INDICADOR4_OPERA(fecha_registro,f_cargar_orden) INDICADOR4,
--F_DIA_FERIADO(fecha_registro) FERIADO,
F_FERIADOS(fecha_registro,f_cargar_orden) FERIADOS,
ROUND(f_cargar_orden - fecha_registro,2) RESTA,
--F_INDICADOR4_OPERA(fecha_registro,f_cargar_orden) RESTA_LABORAL,
TRUNC(f_cargar_orden - fecha_registro) DIAS,
TRUNC(MOD((f_cargar_orden - fecha_registro) * 24, 24)) HORAS,
--TRUNC(MOD((f_cargar_orden - fecha_registro) * (60 * 24), 60)) MINUTOS,
--TRUNC(MOD((f_cargar_orden - fecha_registro) * (60 * 60 * 24), 60)) SEGUNDOS,
F_DIAS_HABILES_JMV(fecha_registro,f_cargar_orden) DIAS_HABILES,
CASE WHEN F_INDICADOR4_OPERA(fecha_registro,f_cargar_orden) = 0 THEN 'NO CUMPLE' ELSE 'SI CUMPLE' END INDICADOR
FROM FACE_FACTURAMZ
WHERE FECHA_EMISION BETWEEN ('01/12/2022') AND ('31/12/2022') AND
TIPO_DOCUMENTO='01' 
AND RUC_PROVEEDOR NOT IN ('20100246768','20100457629') 
AND dar_baja_flag IS NULL AND nume_orden IS NOT NULL
ORDER BY DIAS DESC
--------------------------
SELECT 
--RUC_PROVEEDOR,razon_social,ruc_adquirente,razon_social_adquirente,--decode(TIPO_DOCUMENTO,'01','FACTURA','07','NOTA CREDITO','08','NOTA DEBITO','NO ESPECIFICADO')TIPO_DOCUMENTO,
serie || '-'|| numero_documento nro_doc,
--fecha_emision,
--TRUNC(MOD(((TRUNC(fecha_registro)+18/24) - fecha_registro) * 24, 24)) HORA_1,
fecha_registro AS FECHA_SUBIDA_FACTURA,TO_CHAR(fecha_registro,'DAY') AS DIA_SUBIDA_FACTURA,
--codi_aduan ||'-'|| ano_prese ||'-'|| trim(codi_regi) ||'-'|| nume_orden ORDEN_VINCULADA,
--TRUNC(MOD(((TRUNC(f_cargar_orden)+18/24) - f_cargar_orden) * 24, 24)) HORA_2,
f_cargar_orden AS FECHA_VINCULO_ORDEN,
TO_CHAR(f_cargar_orden,'DAY') AS DIA_VINCULO_ORDEN,
--usuario_cargar_orden AS USUARIO_VINCULO_ORDEN,
DECODE(version_ubl,'2.1','AUTOMATICO','MANUAL') FORMA_SUBIDA_FACTURA,
--F_INDICADOR4_OPERA(fecha_registro,f_cargar_orden) INDICADOR4,
--F_DIA_FERIADO(fecha_registro) FERIADO,
F_FERIADOS(fecha_registro,f_cargar_orden) FERIADOS,
ROUND(f_cargar_orden - fecha_registro,2) RESTA,
--F_INDICADOR4_OPERA(fecha_registro,f_cargar_orden) RESTA_LABORAL,
TRUNC(f_cargar_orden - fecha_registro) DIAS,
TRUNC(MOD((f_cargar_orden - fecha_registro) * 24, 24)) HORAS,
--TRUNC(MOD((f_cargar_orden - fecha_registro) * (60 * 24), 60)) MINUTOS,
--TRUNC(MOD((f_cargar_orden - fecha_registro) * (60 * 60 * 24), 60)) SEGUNDOS,
F_DIAS_HABILES_JMV(fecha_registro,f_cargar_orden) DIAS_HABILES,
--F_DIAS_HABILES(fecha_registro,f_cargar_orden) DIAS_HABILES_X,
CASE WHEN F_INDICADOR4_OPERA(fecha_registro,f_cargar_orden) = 0 THEN 'NO CUMPLE' ELSE 'SI CUMPLE' END INDICADOR
FROM FACE_FACTURAMZ
WHERE FECHA_EMISION BETWEEN ('01/12/2022') AND ('31/12/2022') AND
TIPO_DOCUMENTO='01' 
AND RUC_PROVEEDOR NOT IN ('20100246768','20100457629') 
AND dar_baja_flag IS NULL AND nume_orden IS NOT NULL
ORDER BY DIAS DESC
-------------------------------------------------------
SELECT 
RUC_PROVEEDOR,razon_social,ruc_adquirente,razon_social_adquirente,
decode(TIPO_DOCUMENTO,'01','FACTURA','07','NOTA CREDITO','08','NOTA DEBITO','NO ESPECIFICADO')TIPO_DOCUMENTO,
serie || '-'|| numero_documento nro_doc,
TO_CHAR(fecha_emision,'dd/mm/yyyy') fec_emision,
codi_aduan ||'-'|| ano_prese ||'-'|| trim(codi_regi) ||'-'|| nume_orden ORDEN_VINCULADA,
fecha_registro AS FECHA_SUBIDA_FACTURA,
f_cargar_orden AS FECHA_VINCULO_ORDEN,
usuario_cargar_orden AS USUARIO_VINCULO_ORDEN,
DECODE(version_ubl,'2.1','AUTOMATICO','MANUAL') FORMA_SUBIDA_FACTURA,
CASE WHEN F_INDICADOR4_OPERA(fecha_registro,f_cargar_orden) = 0 THEN 'NO CUMPLE' ELSE 'SI CUMPLE' END INDICADOR
FROM FACE_FACTURAMZ
WHERE FECHA_EMISION BETWEEN ADD_MONTHS(TRUNC(SYSDATE,'MM'),-4) AND LAST_DAY(TRUNC(SYSDATE)) 
AND TIPO_DOCUMENTO='01' 
AND RUC_PROVEEDOR NOT IN ('20100246768','20100457629') 
AND dar_baja_flag IS NULL AND nume_orden IS NOT NULL




----------------------------------INDICADOR 5---------------------------------------------------------------
SELECT 
RUC_PROVEEDOR,razon_social,ruc_adquirente,razon_social_adquirente,decode(TIPO_DOCUMENTO,'01','FACTURA','07','NOTA CREDITO','08','NOTA DEBITO','NO ESPECIFICADO')TIPO_DOCUMENTO,
serie || '-'|| numero_documento nro_doc,TO_CHAR(fecha_emision,'dd/mm/yyyy') FEC_EMISION,
fecha_registro AS FECHA_SUBIDA_FACTURA,
codi_aduan ||'-'|| ano_prese ||'-'|| trim(codi_regi) ||'-'|| nume_orden ORDEN_VINCULADA,
f_cargar_orden AS FECHA_VINCULO_ORDEN,
usuario_cargar_orden AS USUARIO_VINCULO_ORDEN,
DECODE(version_ubl,'2.1','AUTOMATICO','MANUAL') FORMA_SUBIDA_FACTURA
FROM FACE_FACTURAMZ
WHERE FECHA_EMISION BETWEEN ADD_MONTHS(TRUNC(SYSDATE,'MM'),-4) AND LAST_DAY(TRUNC(SYSDATE)) 
AND TIPO_DOCUMENTO='01' 
AND RUC_PROVEEDOR NOT IN ('20100246768','20100457629') 
AND dar_baja_flag IS NULL AND nume_orden IS NOT NULL
