SELECT NUME_ORDEN,CODI_ADUAN,CODI_REGI,CODI_TDESP,NVL(T_DESPACHO,'SIN T_DESPACHO') AS T_DESPACHO,ANO_PRESE,CLIENTE_RAZON_SOCIAL,FEC_USUA_CREA,
TO_CHAR(FEC_DESPACHO,'DD/MM/YYYY') FECHA_DESPACHO,
HORARIO_DESPACHO,
TO_CHAR(FEC_DESPACHO,'MONTH') MES_FECHA_DESPACHO,
FEC_RETIRO,DOC_COMPLETA,
TO_CHAR(FEC_DOC_COMPLETA,'DD/MM/YYYY HH24:MI:SS') FECHA_DOC_COMPLETA,
TO_CHAR(FEC_DOC_COMPLETA,'MONTH') MES_DOC_COMPLETA,
COD_TERMINAL,NOMBRE_ALMACEN,TIPO_DIRECCIONAMIENTO,
DIA_PROGRAMACION AS DIA_PROGRAMAC,
CANT_FERIADO,
TO_CHAR(F_PROG_CORREGIDA(1,FEC_DESPACHO),'DD/MM/YYYY') FECHA_PROG_CORREGIDA,
CASE WHEN DIA_FECHA_COM = 'SÁBADO   ' AND TO_CHAR(FEC_DOC_COMPLETA,'HH24:MI:SS') > '12:00:00'  THEN 'VERDADERO' ELSE 'FALSO' END SABADO_MAS_DE_LAS_12,
TO_CHAR(F_PROG_CORREGIDA(2,FEC_DOC_COMPLETA),'DD/MM/YYYY') FECHA_DOC_CORREGIDA,
DIA_FECHA_COM DIA_FECHA_DOC_COM,
MES_FECHA_COM MES_FECHA_DOC_COM,
CASE WHEN FEC_DOC_COMPLETA IS NOT NULL THEN TO_CHAR(TRUNC(FEC_DOC_COMPLETA,'MM'),'DD/MM/YYYY') ELSE TO_CHAR(TRUNC(FEC_RETIRO,'MM'),'DD/MM/YYYY') END MES_FINAL,
CASE WHEN TRUNC(F_PROG_CORREGIDA(1,FEC_DESPACHO)) > TRUNC(F_PROG_CORREGIDA(2,FEC_DOC_COMPLETA)) THEN TRUNC(F_PROG_CORREGIDA(1,FEC_DESPACHO)) - TRUNC(F_PROG_CORREGIDA(2,FEC_DOC_COMPLETA)) ELSE 0 END DIFERENCIA_DIAS,
CASE WHEN (CODI_ADUAN = '118' AND NOMBRE_ALMACEN ='DP WORLD CALLAO S.R.L.') OR (CODI_ADUAN = '118' AND NOMBRE_ALMACEN ='APM TERMINALS CALLAO S.A.') OR CODI_ADUAN <> '118' THEN 'NO APLICA' ELSE 'APLICA' END VERIFICADOR2,
F_INDICADOR2_MAYRA_JM(FEC_DESPACHO,FEC_DOC_COMPLETA) AS INDICADOR2
FROM(SELECT O.NUME_ORDEN,O.CODI_ADUAN,O.CODI_REGI,O.CODI_TDESP,
    (SELECT DESCRIPCION  FROM TIPO_ANTICIPADO WHERE ADUANA = O.CODI_ADUAN  AND CODIGO = O.TIPO_DESPACHO) AS T_DESPACHO,
    O.ANO_PRESE,
    (SELECT RASON_SOCIAL FROM CLIENTES WHERE CODIGOANT = O.CODI_CLIE AND ROWNUM = 1) CLIENTE_RAZON_SOCIAL,
    A.FEC_USUA_CREA,A.FEC_DESPACHO,
    (SELECT DES_HORARIO FROM HORARIO WHERE COD_HORARIO = A.HOR_PROG) HORARIO_DESPACHO,
    O.FEC_RETIRO,A.DOC_COMPLETA,
    A.FEC_DOC_COMPLETA,
    O.COD_TERMINAL,O.NOMBRE_ALMACEN,
    (SELECT TIPO_DIRECCIONAMIENTO FROM SOLICITUD_VB LEFT JOIN SOLICITUD_VB_ORDEN S ON (S.ANIO_SOLICITUD = SOLICITUD_VB.ANIO_SOLICITUD AND S.NRO_SOLICITUD = SOLICITUD_VB.NRO_SOLICITUD AND S.ORDEN_MADRE = 1) WHERE (SOLICITUD_VB.EMPRESA = '001') AND (S.ANO_PRESE = A.ANO_PRESE) AND (S.NUME_ORDEN = O.NUME_ORDEN) AND ROWNUM = 1) TIPO_DIRECCIONAMIENTO,
    F_DIA_FERIADO(A.FEC_DESPACHO) CANT_FERIADO
    FROM ORDEN O 
    INNER JOIN PROG_DESPACHO_CAB A ON (O.EMPRESA = A.EMPRESA AND O.NUME_ORDEN = A.NUME_ORDEN AND O.CODI_REGI = A.CODI_REGI AND O.CODI_ADUAN = A.CODI_ADUAN AND O.ANO_PRESE = A.ANO_PRESE)
    WHERE TRUNC(O.FEC_RETIRO) BETWEEN TRUNC(TO_DATE('01/10/2022')) AND TRUNC(SYSDATE)) 
ORDER BY NUME_ORDEN ASC;






------------------------------------------------------------------------------------------------------------------------



SELECT O.nume_orden ORDEN,O.codi_aduan ADUANA,O.codi_regi REGIMEN,
DECODE(O.CODI_TDESP,'1-0','Anticipado','0-0','Excepcional','0-1','Urgente','') TIPO_DESPACHO_ORDEN,
(SELECT DESCRIPCION  FROM TIPO_ANTICIPADO  WHERE ADUANA = O.codi_aduan AND codigo = O.tipo_despacho) AS t_despacho,
o.ano_prese AÑO,o.cliente,o.codi_clie,A.fec_usua_crea,A.fec_despacho,
(select des_horario FROM horario WHERE cod_horario=A.hor_prog)horario_despacho,
o.fec_retiro,A.doc_completa,A.fec_doc_completa,o.cod_terminal,
(SELECT NO_ALMACEN FROM ALMAC_ADUANA A WHERE A.COD_ALMAC = O.cod_terminal) NOMBRE_COD_TERMINAL,
CASE WHEN O.CODI_ADUAN <> '235' THEN
    (SELECT nombre_almacen_direccionar FROM SOLICITUD_VB LEFT JOIN solicitud_vb_orden S ON (S.anio_Solicitud=SOLICITUD_VB.ANIO_SOLICITUD AND S.nro_solicitud=SOLICITUD_VB.NRO_SOLICITUD AND S.orden_madre=1) WHERE 
    (SOLICITUD_VB.EMPRESA = '001') AND (s.ano_prese = a.ano_prese ) AND (s.nume_orden = O.nume_orden ) AND rownum=1)
ELSE o.nombre_almacen
END NOMBRE_ALMACEN,
(SELECT TIPO_DIRECCIONAMIENTO FROM SOLICITUD_VB LEFT JOIN solicitud_vb_orden S ON (S.anio_Solicitud=SOLICITUD_VB.ANIO_SOLICITUD AND S.nro_solicitud=SOLICITUD_VB.NRO_SOLICITUD AND S.orden_madre=1) WHERE 
(SOLICITUD_VB.EMPRESA = '001') AND (s.ano_prese = a.ano_prese ) AND (s.nume_orden = O.nume_orden ) AND rownum=1) tipo_direccionamiento
FROM ORDEN O 
INNER JOIN prog_despacho_cab A ON O.EMPRESA=a.EMPRESA AND  O.nume_orden=a.nume_orden AND O.codi_regi=a.codi_regi AND o.codi_aduan=a.codi_aduan AND o.ano_prese=a.ano_prese
WHERE 
TRUNC(O.fec_retiro) BETWEEN  TO_DATE('01/12/2022','dd/mm/yyyy') AND TO_DATE('31/12/2022','dd/mm/yyyy')
order by O.fec_retiro ASC


-----------------------------------------

SELECT ORDEN,ADUANA,REGIMEN,AÑO,FEC_DESPACHO,FEC_DOC_COMPLETA,NOMBRE_TERMINAL,tipo_direccionamiento,ADU118_REGI10,APM_DPW,

F_INDICADOR1_OPERA(ADUANA,REGIMEN,NOMBRE_TERMINAL,tipo_direccionamiento,FEC_DOC_COMPLETA,FEC_DESPACHO) INDICADOR

FROM
    (SELECT O.NUME_ORDEN ORDEN,O.CODI_ADUAN ADUANA,O.CODI_REGI REGIMEN,
    DECODE(O.CODI_TDESP,'1-0','Anticipado','0-0','Excepcional','0-1','Urgente','') TIPO_DESPACHO_ORDEN,
    (SELECT DESCRIPCION FROM TIPO_ANTICIPADO WHERE ADUANA = O.CODI_ADUAN AND CODIGO = O.tipo_despacho) AS t_despacho,
    O.ANO_PRESE AÑO,O.CLIENTE,O.CODI_CLIE,A.fec_usua_crea,A.fec_despacho,
    (SELECT DES_HORARIO FROM HORARIO WHERE COD_HORARIO = A.hor_prog)horario_despacho,
    O.FEC_RETIRO,A.doc_completa,A.fec_doc_completa,
    (SELECT RAZ_SOCIAL FROM ALMAC_ADUANA A WHERE A.COD_ALMAC = O.COD_TERMINAL) NOMBRE_TERMINAL,
    (SELECT TIPO_DIRECCIONAMIENTO FROM SOLICITUD_VB LEFT JOIN solicitud_vb_orden S ON (S.ANIO_SOLICITUD=SOLICITUD_VB.ANIO_SOLICITUD AND S.nro_solicitud = SOLICITUD_VB.NRO_SOLICITUD AND S.ORDEN_MADRE = 1) WHERE 
    (SOLICITUD_VB.EMPRESA = '001') AND (s.ANO_PRESE = A.ANO_PRESE ) AND (s.NUME_ORDEN = O.NUME_ORDEN ) AND ROWNUM=1) tipo_direccionamiento,
    CASE WHEN O.CODI_ADUAN = '118' AND O.CODI_REGI = '10' THEN 'SI' ELSE 'NO' END ADU118_REGI10,
    CASE WHEN O.COD_TERMINAL IN ('4004','3014') THEN 'SI' ELSE 'NO' END APM_DPW
    FROM ORDEN O 
    INNER JOIN prog_despacho_cab A ON (O.EMPRESA = A.EMPRESA AND O.NUME_ORDEN = A.NUME_ORDEN AND O.CODI_REGI = A.CODI_REGI AND O.CODI_ADUAN = A.CODI_ADUAN AND O.ANO_PRESE = A.ANO_PRESE)
    WHERE 
    (F_ORDEN_PARCIAL(O.CODI_ADUAN,O.CODI_REGI,O.ANO_PRESE,O.NUME_ORDEN) = 0) 
    AND O.CODI_ADUAN NOT IN ('40','60','50','52')
    AND TRUNC(O.FEC_RETIRO) BETWEEN  TO_DATE('01/12/2022','dd/mm/yyyy') AND TO_DATE('31/12/2022','dd/mm/yyyy'))
--ORDER BY ORDEN ASC





----------------------------------------------------------------------------------


SELECT ORDEN,ADUANA,REGIMEN,AÑO,FEC_DOC_COMPLETA,FEC_DESPACHO-1 DIA_MENOS_FEC_DESPACHO,FEC_DESPACHO,NOMBRE_TERMINAL,TIPO_DIRECCIONAMIENTO,ADU118_REGI10,APM_DPW,

F_INDICADOR1_OPERA(ADUANA,REGIMEN,NOMBRE_TERMINAL,TIPO_DIRECCIONAMIENTO,FEC_DOC_COMPLETA,FEC_DESPACHO) INDICADOR

FROM
    (SELECT O.NUME_ORDEN ORDEN,O.CODI_ADUAN ADUANA,O.CODI_REGI REGIMEN,
    DECODE(O.CODI_TDESP,'1-0','Anticipado','0-0','Excepcional','0-1','Urgente','') TIPO_DESPACHO_ORDEN,
    (SELECT DESCRIPCION FROM TIPO_ANTICIPADO WHERE ADUANA = O.CODI_ADUAN AND CODIGO = O.tipo_despacho) AS t_despacho,
    O.ANO_PRESE AÑO,O.CLIENTE,O.CODI_CLIE,A.fec_usua_crea,A.fec_despacho,
    (SELECT DES_HORARIO FROM HORARIO WHERE COD_HORARIO = A.hor_prog)horario_despacho,
    O.FEC_RETIRO,A.doc_completa,A.fec_doc_completa,
    (SELECT RAZ_SOCIAL FROM ALMAC_ADUANA A WHERE A.COD_ALMAC = O.COD_TERMINAL) NOMBRE_TERMINAL,
    (SELECT TIPO_DIRECCIONAMIENTO FROM SOLICITUD_VB LEFT JOIN solicitud_vb_orden S ON (S.ANIO_SOLICITUD=SOLICITUD_VB.ANIO_SOLICITUD AND S.nro_solicitud = SOLICITUD_VB.NRO_SOLICITUD AND S.ORDEN_MADRE = 1) WHERE 
    (SOLICITUD_VB.EMPRESA = '001') AND (s.ANO_PRESE = A.ANO_PRESE ) AND (s.NUME_ORDEN = O.NUME_ORDEN ) AND ROWNUM=1) TIPO_DIRECCIONAMIENTO,
    CASE WHEN O.CODI_ADUAN = '118' AND O.CODI_REGI = '10' THEN 'SI' ELSE 'NO' END ADU118_REGI10,
    CASE WHEN O.COD_TERMINAL IN ('4004','3014') THEN 'SI' ELSE 'NO' END APM_DPW
    FROM ORDEN O 
    INNER JOIN prog_despacho_cab A ON (O.EMPRESA = A.EMPRESA AND O.NUME_ORDEN = A.NUME_ORDEN AND O.CODI_REGI = A.CODI_REGI AND O.CODI_ADUAN = A.CODI_ADUAN AND O.ANO_PRESE = A.ANO_PRESE)
    WHERE 
    (F_ORDEN_PARCIAL(O.CODI_ADUAN,O.CODI_REGI,O.ANO_PRESE,O.NUME_ORDEN) = 0) 
    AND O.CODI_ADUAN NOT IN ('40','60','50','52')
    AND TRUNC(O.FEC_RETIRO) BETWEEN  TO_DATE('01/12/2022','dd/mm/yyyy') AND TO_DATE('31/12/2022','dd/mm/yyyy'))
--ORDER BY ORDEN ASC
