CREATE OR REPLACE VIEW V_PRODUCTIVIDAD_EXPO AS 
SELECT 
(select rason_social from clientes where codigoant=codi_clie AND ROWNUM=1) CLIENTE,
(SELECT PESO_EXPO FROM CLIENTES WHERE CODIGOANT IS NOT NULL AND CODIGOANT = CODI_CLIE AND EMPRESA='001') PESO,
TO_CHAR(FECHA_NUME_PROVI,'MM') MES,
(SELECT PNOMBRE ||' '|| SNOMBRE ||' '|| APATERNO ||' '|| AMATERNO  FROM TRABAJADORES WHERE COD_ASCINSA = COMERCIAL AND ROWNUM=1) COMERCIAL,
(select PNOMBRE || ' ' || SNOMBRE|| ' ' ||APATERNO|| ' ' || AMATERNO FROM TRABAJADORES t WHERE t.ctrabajador = (SELECT jefe_inmediato  FROM trabajadores r WHERE COMERCIAL = r.cod_ascinsa )) JEFE_INMEDIATO, 
COUNT(*) TOTAL,
F_TOTALXPESO_EXPO(CODI_CLIE,COUNT(*)) CANTXPESO
FROM ORDEN WHERE ANO_PRESE = TO_CHAR(sysdate,'YYYY') AND codi_regi = '40' AND flag_parcial_deposito = '0' AND FECHA_NUME_PROVI IS NOT NULL
GROUP BY CODI_CLIE,TO_CHAR(FECHA_NUME_PROVI,'MM'),COMERCIAL
ORDER BY CODI_CLIE,TO_CHAR(FECHA_NUME_PROVI,'MM'),COMERCIAL;




SELECT CLIENTE,COMERCIAL,JEFE_INMEDIATO,
'01' ||'/'|| MES ||'/'|| TO_CHAR(SYSDATE,'YYYY')  FECHA,PESO,TOTAL,CANTXPESO
FROM V_PRODUCTIVIDAD_EXPO;

SELECT * FROM AUD014 WHERE ANO_PRESE = '2022';

----------------------------------------------------------------------------------------
SELECT 
--COUNT(1)TOTAL
NVL(O.FEC_NUMERACION_W,O.FEC_NUMERACION) FEC_NUMERACION,O.CODI_REGI,O.NUME_ORDEN, O.CLIENTE, O.CODI_CLIE, OI.COMERCIAL 
FROM ORDEN O
LEFT JOIN ORDEN_INDICADOR_JM OI ON (O.ANO_PRESE = OI.ANO_PRESE AND O.CODI_REGI = OI.CODI_REGI AND O.CODI_ADUAN = OI.CODI_ADUAN AND O.EMPRESA = OI.EMPRESA AND O.NUME_ORDEN = OI.NUME_ORDEN)
WHERE O.ANO_PRESE= '2022' AND (NVL(O.FEC_NUMERACION_W,O.FEC_NUMERACION) BETWEEN '01/01/2022' AND '31/12/2022') AND O.CODI_REGI NOT IN ('40','52')
AND O.CODI_CLIE = 'PE0031'
--AND OI.COMERCIAL <> 'KVL001'
ORDER BY NVL(O.FEC_NUMERACION_W,O.FEC_NUMERACION) ASC
;

SELECT 
--COUNT(1)TOTAL
O.CODI_REGI,O.NUME_ORDEN, O.CLIENTE, O.CODI_CLIE, OI.COMERCIAL 
FROM ORDEN O
LEFT JOIN ORDEN_INDICADOR_JM OI ON (O.ANO_PRESE = OI.ANO_PRESE AND O.CODI_REGI = OI.CODI_REGI AND O.CODI_ADUAN = OI.CODI_ADUAN AND O.EMPRESA = OI.EMPRESA AND O.NUME_ORDEN = OI.NUME_ORDEN)
WHERE O.ANO_PRESE= '2022' AND TO_CHAR(NVL(O.FEC_NUMERACION_W,O.FEC_NUMERACION),'MM') = '01' AND O.CODI_REGI NOT IN ('40','52')
AND O.CODI_CLIE = 'PE0006'
AND OI.COMERCIAL <> 'ICP002'
;


UPDATE ORDEN_INDICADOR_JM SET COMERCIAL= 'KVL001' WHERE COMERCIAL IN ('ESS001') AND CODI_CLIE IN ('PE0031') 
AND NUME_ORDEN IN ('005902');

COMMIT;
ROLLBACK;


SELECT COMERCIAL,CODI_CLIE FROM ORDEN_INDICADOR_JM WHERE NUME_ORDEN = '005902'


----------------------------------------------------------------------------------------------------------------------------------------------------------


SELECT O.NUME_ORDEN,OD.FECHA_DOC_EMBARQUE, 
OD.PUERTO_EMBARQUE,OD.SERIE
FROM ORDEN O
INNER JOIN ORDEN_DETALLE OD ON (O.EMPRESA = OD.EMPRESA AND O.ANO_PRESE = OD.ANO_PRESE AND O.CODI_REGI = OD.CODI_REGI AND O.CODI_ADUAN = OD.CODI_ADUAN AND O.NUME_ORDEN = OD.NUME_ORDEN)
WHERE O.ANO_PRESE = '2022' 
--AND TO_CHAR(NVL(O.FEC_NUMERACION_W, O.FEC_NUMERACION),'MM') = '08'
AND OD.SERIE = O.TOTAL_SERIES
--(SELECT MAX(SERIE) FROM ORDEN_DETALLE WHERE NUME_ORDEN = OD.NUME_ORDEN AND EMPRESA = OD.EMPRESA AND ANO_PRESE = OD.ANO_PRESE AND CODI_ADUAN  = OD.CODI_ADUAN AND CODI_REGI = OD.CODI_REGI)
AND o.nume_orden IN ('000459','000615','010227','009320','010864','010989','011508','000104','')
GROUP BY O.NUME_ORDEN,OD.FECHA_DOC_EMBARQUE, OD.PAIS_ORIGEN,OD.PUERTO_EMBARQUE,OD.SERIE;

SELECT *
--NUME_ORDEN,PAIS_ORIGEN,PUERTO_EMBARQUE
--MAX(SERIE) 

FROM ORDEN_DETALLE WHERE NUME_ORDEN = '010864' AND EMPRESA = '001' AND ANO_PRESE = '2022' 
--AND CODI_ADUAN  = '118'  AND CODI_REGI = '10';

;

-------------------------


SELECT A.ANO_PRESE AÑO,A.NUME_ORDEN ORDEN,A.CODI_REGI REGIMEN, A.CODI_ADUAN ADUANA,
(SELECT  RASON_SOCIAL FROM CLIENTES C WHERE C.CODIGOANT = O.CODI_CLIE AND ROWNUM=1) CLIENTE,
(SELECT COUNT(1) FROM ORDEN_DETALLE OD WHERE OD.EMPRESA = O.EMPRESA AND OD.ANO_PRESE = O.ANO_PRESE AND OD.CODI_ADUAN = O.CODI_ADUAN AND TRIM(OD.CODI_REGI)=TRIM(O.CODI_REGI) AND OD.NUME_ORDEN = O.NUME_ORDEN) SERIES,
A.NUME_REGI SECUENCIA, A.FCH_INC FECHA_INCIDENCIA,
NVL(O.FEC_NUMERACION_W, O.FEC_NUMERACION) FECHA_NUMERA,
A.CODI_INC COD_INC,A.INCIDENCIA,A.USUARIOS,
(SELECT  PNOMBRE ||' '|| SNOMBRE ||' '|| APATERNO ||' '|| AMATERNO FROM TRABAJADORES T WHERE T.COD_ASCINSA = A.USUARIOS) NOMBRE_USUARIO
FROM ADU014 A 
INNER JOIN ORDEN O ON (O.ANO_PRESE = A.ANO_PRESE AND O.CODI_REGI = A.CODI_REGI AND O.CODI_ADUAN = A.CODI_ADUAN AND O.NUME_ORDEN = A.NUME_ORDEN)
WHERE A.CODI_INC = 'F02' AND A.ANO_PRESE = '2022' 
--AND TO_CHAR(A.FCH_INC,'MM') ='08'
--AND A.NUME_ORDEN = '009132' 
;
-----------------------------------------------------------

SELECT * FROM ADU014  WHERE NUME_ORDEN = '010242' AND ANO_PRESE = '2022' and nume_regi='92'
--AND CODI_INC = 'F02'

;

SELECT * FROM ADU014
WHERE  
(SYSDATE - 1) <= fch_inc AND CODI_REGI IS NOT NULL AND CODI_ADUAN IS NOT NULL AND ANO_PRESE IS NOT NULL AND NUME_ORDEN IS NOT NULL
AND TRIM(CODI_REGI)<>'' AND TRIM(CODI_ADUAN)<>'' AND TRIM(ANO_PRESE)<>'' AND TRIM(NUME_ORDEN)<>'' AND TO_CHAR(fch_inc,'MM') = '08';







