--CREATE OR REPLACE FORCE VIEW VISTA_REPORTEENVIOLLEGADA AS 
  SELECT NUME_ORDEN,PAIS,PUERTO,REGIMEN,ADUANA,AÑO,CLIENTE,TIPO_CLIENTE,NRO_SERIES,FECHA_INGRESO_PRODUCCION,ETA,
      CASE WHEN  FECHA_NUMERACION IS NULL THEN 'x'
           ELSE 'OK'
      END VERIFICADOR1,
      FECHA_NUMERACION,FECHA_LLEGADA,
      NVL(F_OBTENER_TIPO_DIA(FECHA_LLEGADA),'NO DEFINIDO') Desc_Dia_Llegada,
      NVL(F_VALIDAR_COR_HOR_LABORAL(CLIENTE,FECHA_LLEGADA,ADUANA,1),'NO DEFINIDO') CORTE_LLEGADA,
      FECHA_ULTIMO_ENVIO,
      NVL(F_OBTENER_TIPO_DIA(FECHA_ULTIMO_ENVIO),'NO DEFINIDO') Desc_Dia_envio,
      NVL(F_VALIDAR_COR_HOR_LABORAL(CLIENTE,FECHA_ULTIMO_ENVIO,ADUANA,2),'NO DEFINIDO') CORTE_ULT_ENV,
      NVL(F_VERIFICADOR3(F_OBTENER_TIPO_DIA(FECHA_LLEGADA),F_VALIDAR_COR_HOR_LABORAL(CLIENTE,FECHA_LLEGADA,ADUANA,1),F_OBTENER_TIPO_DIA(FECHA_ULTIMO_ENVIO),F_VALIDAR_COR_HOR_LABORAL(CLIENTE,FECHA_ULTIMO_ENVIO,ADUANA,2)),'NO ENCONTRADOV3') VERIFICADOR3,
      F_DIAS_HABILES_JMV(TRUNC(FECHA_ULTIMO_ENVIO),TRUNC(FECHA_LLEGADA)) DIFERENCIA_DIAS,
      CASE  WHEN MODALIDAD = 'Anticipado' THEN  'REVISAR INDICADOR'
            ELSE 'FUERA DE ALCANCE'
      END VERIFICADOR2,
      F_DIF_LLEGADA_ULTENVIO(FECHA_LLEGADA,FECHA_ULTIMO_ENVIO,TIPO_CLIENTE,F_DIAS_HABILES_JMV(TRUNC(FECHA_ULTIMO_ENVIO),TRUNC(FECHA_LLEGADA)),F_VERIFICADOR3(F_OBTENER_TIPO_DIA(FECHA_LLEGADA),F_VALIDAR_COR_HOR_LABORAL(CLIENTE,FECHA_LLEGADA,ADUANA,1),F_OBTENER_TIPO_DIA(FECHA_ULTIMO_ENVIO),F_VALIDAR_COR_HOR_LABORAL(CLIENTE,FECHA_ULTIMO_ENVIO,ADUANA,2))) ANALISIS,
      MODALIDAD,COMERCIAL
FROM (SELECT OI.NUME_ORDEN,OI.CODI_REGI REGIMEN,OI.CODI_ADUAN ADUANA,OI.ANO_PRESE AÑO,O.CLIENTE,O.FECHA_INICIO_PRODUCCION FECHA_INGRESO_PRODUCCION,F_TIPO_CLIENTE(o.CLIENTE,OI.CODI_ADUAN) TIPO_CLIENTE,O.COMERCIAL COMERCIAL,
     (SELECT COUNT(1) FROM ORDEN_DETALLE OD WHERE OD.EMPRESA = O.EMPRESA AND OD.ANO_PRESE = O.ANO_PRESE AND OD.CODI_ADUAN = O.CODI_ADUAN AND TRIM(OD.CODI_REGI) = TRIM(O.CODI_REGI) AND OD.NUME_ORDEN = O.NUME_ORDEN) NRO_SERIES,
     OI.FEC_ITERACION FECHA_ULTIMO_ENVIO,
     F_FECHA_ETA_VBF(O.EMPRESA,O.ANO_PRESE,O.CODI_ADUAN,TRIM(O.CODI_REGI),O.NUME_ORDEN) ETA,
     NVL(O.FEC_NUMERACION_W, O.FEC_NUMERACION) FECHA_NUMERACION,
     NVL(F_FECHA_LLEGADA(O.EMPRESA,O.ANO_MANIFIESTO,O.CODI_ADUAN,O.NRO_MANIFIESTO), O.FECHA_LLEGADA) FECHA_LLEGADA,
     ET.DESCRIPCION,OI.ITERACION,
	 DECODE(O.CODI_TDESP,'1-0','Anticipado','0-0','Excepcional','0-1','Urgente','') MODALIDAD,
     OD.PAIS_ORIGEN AS PAIS,OD.PUERTO_EMBARQUE AS PUERTO
     FROM ORDEN_ITERACIONES_PROD OI INNER JOIN ORDEN O ON OI.ANO_PRESE = O.ANO_PRESE AND OI.EMPRESA=o.EMPRESA AND TRIM(OI.codi_aduan)=TRIM(O.CODI_ADUAN) AND TRIM(OI.CODI_REGI) = TRIM(O.CODI_REGI) AND OI.NUME_ORDEN = O.NUME_ORDEN
     LEFT JOIN ORDEN_ETAPAS ET ON OI.EMPRESA = ET.EMPRESA AND OI.ETAPA = ET.CODIGO
     INNER JOIN ORDEN_DETALLE OD ON (O.EMPRESA = OD.EMPRESA AND O.ANO_PRESE = OD.ANO_PRESE AND O.CODI_REGI = OD.CODI_REGI AND O.CODI_ADUAN = OD.CODI_ADUAN AND O.NUME_ORDEN = OD.NUME_ORDEN)
     WHERE (O.FLAG_TIPO_LINEA = 1 OR O.FLAG_TIPO_LINEA = 2) AND OI.EMPRESA='001' AND TO_CHAR(OI.FEC_ITERACION,'YYYY') = TO_CHAR(SYSDATE,'YYYY') AND TO_CHAR(OI.FEC_ITERACION,'MM') = '08'
     AND OI.FEC_ITERACION = (select max(FEC_ITERACION) FROM ORDEN_ITERACIONES_PROD WHERE NUME_ORDEN = OI.NUME_ORDEN AND EMPRESA = OI.EMPRESA AND ANO_PRESE = OI.ANO_PRESE)
     AND OD.SERIE = (SELECT MAX(SERIE) FROM ORDEN_DETALLE WHERE NUME_ORDEN = OD.NUME_ORDEN AND EMPRESA = OD.EMPRESA AND ANO_PRESE = OD.ANO_PRESE AND CODI_ADUAN  = OD.CODI_ADUAN AND CODI_REGI = OD.CODI_REGI)
     ORDER BY OI.FEC_ITERACION, OI.NUME_ORDEN);
-----------------------------------

CREATE OR REPLACE VIEW V_PRODUCTIVIDAD_EXPO AS 
SELECT 
(select rason_social from clientes where codigoant=codi_clie AND ROWNUM=1) CLIENTE,
(SELECT PESO FROM CLIENTES WHERE CODIGOANT IS NOT NULL AND CODIGOANT = CODI_CLIE AND EMPRESA='001') PESO,
TO_CHAR(FECHA_NUME_PROVI,'MM') MES,
(SELECT PNOMBRE ||' '|| SNOMBRE ||' '|| APATERNO ||' '|| AMATERNO  FROM TRABAJADORES WHERE COD_ASCINSA = COMERCIAL AND ROWNUM=1) COMERCIAL,
(select PNOMBRE || ' ' || SNOMBRE|| ' ' ||APATERNO|| ' ' || AMATERNO FROM TRABAJADORES t WHERE t.ctrabajador = (SELECT jefe_inmediato  FROM trabajadores r WHERE COMERCIAL = r.cod_ascinsa )) JEFE_INMEDIATO, 
COUNT(*) TOTAL,
F_TOTALXPESO(CODI_CLIE,COUNT(*)) CANTXPESO
FROM ORDEN WHERE ANO_PRESE = TO_CHAR(sysdate,'YYYY') AND codi_regi = '40' AND flag_parcial_deposito = '0'
GROUP BY CLIENTE,CODI_CLIE,TO_CHAR(FECHA_NUME_PROVI,'MM'),COMERCIAL
ORDER BY CLIENTE,CODI_CLIE,TO_CHAR(FECHA_NUME_PROVI,'MM'),COMERCIAL;


SELECT CLIENTE,COMERCIAL,JEFE_INMEDIATO,
'01' ||'/'|| MES ||'/'|| TO_CHAR(SYSDATE,'YYYY')  FECHA,PESO,TOTAL,CANTXPESO
FROM V_PRODUCTIVIDAD_EXPO 

-----------------------------------------------

SELECT COUNT(*)
FROM ORDEN WHERE ANO_PRESE = '2022';

SELECT COUNT(*)
FROM ORDEN_INDICADOR_JM WHERE ANO_PRESE = '2022';
--------------------------------------------------------------------------

SELECT NUME_ORDEN,REGIMEN,ADUANA,AÑO,CLIENTE,TIPO_CLIENTE,NRO_SERIES,FECHA_INGRESO_PRODUCCION,ETA,VERIFICADOR1,FECHA_NUMERACION,FECHA_LLEGADA,DESC_DIA_LLEGADA,CORTE_LLEGADA,FECHA_ULTIMO_ENVIO,CORTE_ULT_ENV,VERIFICADOR3,DIFERENCIA_DIAS,VERIFICADOR2,ANALISIS,MODALIDAD,
F_DESC_ANALISIS1(VERIFICADOR2,ANALISIS)DESC_ANALISIS1,F_DESC_ANALISIS2(VERIFICADOR2,ANALISIS) DESC_ANALISIS2,
(SELECT pnombre || ' ' || snombre|| ' ' || apaterno|| ' ' ||amaterno FROM trabajadores t where COMERCIAL = t.cod_ascinsa ) NOM_COMERCIAL,
(SELECT pnombre || ' ' || snombre|| ' ' || apaterno|| ' ' ||amaterno FROM trabajadores t where t.ctrabajador = (SELECT jefe_inmediato  FROM trabajadores r where COMERCIAL = r.cod_ascinsa )) JEFE_COMERCIAL
FROM VISTA_REPORTEENVIOLLEGADA;





SELECT O.NUME_ORDEN,OD.FECHA_DOC_EMBARQUE, OD.PAIS_ORIGEN,OD.PUERTO_EMBARQUE,OD.SERIE
FROM ORDEN O
INNER JOIN ORDEN_DETALLE OD ON (O.EMPRESA = OD.EMPRESA AND O.ANO_PRESE = OD.ANO_PRESE AND O.CODI_REGI = OD.CODI_REGI AND O.CODI_ADUAN = OD.CODI_ADUAN AND O.NUME_ORDEN = OD.NUME_ORDEN)
WHERE O.ANO_PRESE = '2022' 
--AND TO_CHAR(NVL(O.FEC_NUMERACION_W, O.FEC_NUMERACION),'MM') = '08'
AND OD.SERIE = (SELECT MAX(SERIE) FROM ORDEN_DETALLE WHERE NUME_ORDEN = OD.NUME_ORDEN AND EMPRESA = OD.EMPRESA AND ANO_PRESE = OD.ANO_PRESE AND CODI_ADUAN  = OD.CODI_ADUAN AND CODI_REGI = OD.CODI_REGI)
AND o.nume_orden IN ('000459','000615','010227','009320')
GROUP BY O.NUME_ORDEN,OD.FECHA_DOC_EMBARQUE, OD.PAIS_ORIGEN,OD.PUERTO_EMBARQUE,OD.SERIE;
--HAVING MAX(OD.SERIE);

SELECT MAX(SERIE) FROM ORDEN_DETALLE WHERE NUME_ORDEN = '000459' AND EMPRESA = '001' AND ANO_PRESE = '2022' AND CODI_ADUAN  = '118'  AND CODI_REGI = '10';



-------------------------


SELECT A.ANO_PRESE AÑO,A.NUME_ORDEN ORDEN,A.CODI_REGI REGIMEN, A.CODI_ADUAN ADUANA,
(SELECT  RASON_SOCIAL FROM CLIENTES C WHERE C.CODIGOANT = O.CODI_CLIE AND ROWNUM=1) CLIENTE,
(SELECT COUNT(1) FROM ORDEN_DETALLE OD WHERE OD.EMPRESA = O.EMPRESA AND OD.ANO_PRESE = O.ANO_PRESE AND OD.CODI_ADUAN = O.CODI_ADUAN AND TRIM(OD.CODI_REGI)=TRIM(O.CODI_REGI) AND OD.NUME_ORDEN = O.NUME_ORDEN) SERIES,
A.NUME_REGI SECUENCIA, A.FCH_INC FECHA_INCIDENCIA,
NVL(O.FEC_NUMERACION_W, O.FEC_NUMERACION) FECHA_NUMERA,
A.CODI_INC COD_INC,A.INCIDENCIA,A.USUARIOS,
(SELECT  PNOMBRE ||' '|| SNOMBRE ||' '|| APATERNO ||' '|| AMATERNO FROM TRABAJADORES T WHERE T.COD_ASCINSA = A.USUARIOS) NOMBRE_USUARIO
FROM ADU014 A 
INNER JOIN ORDEN O ON (O.ANO_PRESE = A.ANO_PRESE AND O.CODI_REGI = A.CODI_REGI AND O.CODI_ADUAN = A.CODI_ADUAN AND O.NUME_ORDEN = A.NUME_ORDEN)
WHERE A.CODI_INC = 'F02' AND A.ANO_PRESE = '2022' 
--AND A.NUME_ORDEN = '009132' 

-----------------------------------------------------------



SELECT NUME_ORDEN FROM ORDEN WHERE ANO_PRESE = '2022' AND CODI_REGI = '40';

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------

CREATE OR REPLACE VIEW VISTA_REPORTE_ENVIO_LLEGADA AS 
  SELECT /*+ result_cache */ NUME_ORDEN,PAIS,PUERTO,REGIMEN,ADUANA,AÑO,CLIENTE,TIPO_CLIENTE,NRO_SERIES,FECHA_INGRESO_PRODUCCION,ETA,
      CASE WHEN  FECHA_NUMERACION IS NULL THEN 'x'
           ELSE 'OK'
      END VERIFICADOR1,
      FECHA_NUMERACION,FECHA_LLEGADA,
      NVL(F_OBTENER_TIPO_DIA(FECHA_LLEGADA),'NO DEFINIDO') Desc_Dia_Llegada,
      NVL(F_VALIDAR_COR_HOR_LABORAL(CLIENTE,FECHA_LLEGADA,ADUANA,1),'NO DEFINIDO') CORTE_LLEGADA,
      FECHA_ULTIMO_ENVIO,
      NVL(F_OBTENER_TIPO_DIA(FECHA_ULTIMO_ENVIO),'NO DEFINIDO') Desc_Dia_envio,
      NVL(F_VALIDAR_COR_HOR_LABORAL(CLIENTE,FECHA_ULTIMO_ENVIO,ADUANA,2),'NO DEFINIDO') CORTE_ULT_ENV,
      NVL(F_VERIFICADOR3(F_OBTENER_TIPO_DIA(FECHA_LLEGADA),F_VALIDAR_COR_HOR_LABORAL(CLIENTE,FECHA_LLEGADA,ADUANA,1),F_OBTENER_TIPO_DIA(FECHA_ULTIMO_ENVIO),F_VALIDAR_COR_HOR_LABORAL(CLIENTE,FECHA_ULTIMO_ENVIO,ADUANA,2)),'NO ENCONTRADOV3') VERIFICADOR3,
      F_DIAS_HABILES_JMV(TRUNC(FECHA_ULTIMO_ENVIO),TRUNC(FECHA_LLEGADA)) DIFERENCIA_DIAS,
      CASE  WHEN MODALIDAD = 'Anticipado' THEN  'REVISAR INDICADOR'
            ELSE 'FUERA DE ALCANCE'
      END VERIFICADOR2,
      F_DIF_LLEGADA_ULTENVIO(FECHA_LLEGADA,FECHA_ULTIMO_ENVIO,TIPO_CLIENTE,F_DIAS_HABILES_JMV(TRUNC(FECHA_ULTIMO_ENVIO),TRUNC(FECHA_LLEGADA)),F_VERIFICADOR3(F_OBTENER_TIPO_DIA(FECHA_LLEGADA),F_VALIDAR_COR_HOR_LABORAL(CLIENTE,FECHA_LLEGADA,ADUANA,1),F_OBTENER_TIPO_DIA(FECHA_ULTIMO_ENVIO),F_VALIDAR_COR_HOR_LABORAL(CLIENTE,FECHA_ULTIMO_ENVIO,ADUANA,2))) ANALISIS,
      MODALIDAD,NOMBRE_COMERCIAL,JEFE_COMERCIAL
FROM (SELECT /*+ result_cache */ OI.NUME_ORDEN,OI.CODI_REGI REGIMEN,OI.CODI_ADUAN ADUANA,OI.ANO_PRESE AÑO,O.CLIENTE,O.FECHA_INICIO_PRODUCCION FECHA_INGRESO_PRODUCCION,F_TIPO_CLIENTE(o.CLIENTE,OI.CODI_ADUAN) TIPO_CLIENTE,
      (SELECT pnombre || ' ' || snombre|| ' ' || apaterno|| ' ' ||amaterno FROM trabajadores t where JM.COMERCIAL = t.cod_ascinsa ) NOMBRE_COMERCIAL,
      (SELECT pnombre || ' ' || snombre|| ' ' || apaterno|| ' ' ||amaterno FROM trabajadores t where t.ctrabajador = (SELECT jefe_inmediato  FROM trabajadores r where JM.COMERCIAL = r.cod_ascinsa )) JEFE_COMERCIAL,
      O.TOTAL_SERIES  NRO_SERIES,
     OI.FEC_ITERACION FECHA_ULTIMO_ENVIO,
     F_FECHA_ETA_VBF(O.EMPRESA,O.ANO_PRESE,O.CODI_ADUAN,TRIM(O.CODI_REGI),O.NUME_ORDEN) ETA,
     NVL(O.FEC_NUMERACION_W, O.FEC_NUMERACION) FECHA_NUMERACION,
     NVL(F_FECHA_LLEGADA(O.EMPRESA,O.ANO_MANIFIESTO,O.CODI_ADUAN,O.NRO_MANIFIESTO), O.FECHA_LLEGADA) FECHA_LLEGADA,
     ET.DESCRIPCION,OI.ITERACION,
	 DECODE(O.CODI_TDESP,'1-0','Anticipado','0-0','Excepcional','0-1','Urgente','') MODALIDAD,
     CASE WHEN (OD.PUERTO_EMBARQUE IS NOT NULL ) THEN
        NVL(F_OBTE_PAIS_PUERTO_EMB(OD.PUERTO_EMBARQUE),OD.PAIS_ORIGEN)
     END AS PAIS,
     OD.PUERTO_EMBARQUE AS PUERTO
     FROM ORDEN_ITERACIONES_PROD OI 
     INNER JOIN ORDEN O ON OI.ANO_PRESE = O.ANO_PRESE AND OI.EMPRESA=o.EMPRESA AND TRIM(OI.codi_aduan)=TRIM(O.CODI_ADUAN) AND TRIM(OI.CODI_REGI) = TRIM(O.CODI_REGI) AND OI.NUME_ORDEN = O.NUME_ORDEN
     LEFT JOIN ORDEN_ETAPAS ET ON OI.EMPRESA = ET.EMPRESA AND OI.ETAPA = ET.CODIGO
     INNER JOIN ORDEN_DETALLE OD ON (O.EMPRESA = OD.EMPRESA AND O.ANO_PRESE = OD.ANO_PRESE AND O.CODI_REGI = OD.CODI_REGI AND O.CODI_ADUAN = OD.CODI_ADUAN AND O.NUME_ORDEN = OD.NUME_ORDEN)
     LEFT  JOIN ORDEN_INDICADOR_JM JM ON (O.EMPRESA = JM.EMPRESA AND O.ANO_PRESE = JM.ANO_PRESE AND O.CODI_REGI = JM.CODI_REGI AND O.CODI_ADUAN = JM.CODI_ADUAN AND O.NUME_ORDEN = JM.NUME_ORDEN)
     WHERE (O.FLAG_TIPO_LINEA = 1 OR O.FLAG_TIPO_LINEA = 2) AND OI.EMPRESA='001' AND TO_CHAR(OI.FEC_ITERACION,'YYYY') = TO_CHAR(SYSDATE,'YYYY')
     AND OI.FEC_ITERACION = (select max(FEC_ITERACION) FROM ORDEN_ITERACIONES_PROD WHERE NUME_ORDEN = OI.NUME_ORDEN AND EMPRESA = OI.EMPRESA AND ANO_PRESE = OI.ANO_PRESE)
     AND OD.SERIE = O.TOTAL_SERIES
     ORDER BY OI.FEC_ITERACION, OI.NUME_ORDEN)


