INSERT INTO orden_indicador_jm (ANO_PRESE,
CODI_ADUAN,
CODI_CLIE,
CODI_REGI,
COMERCIAL,
EMPRESA,
FECHA_UPDATE,
NUME_ORDEN,
USER_UPDATE)
SELECT ANO_PRESE,CODI_ADUAN ,CODI_CLIE, CODI_REGI, COMERCIAL , A.EMPRESA, FEC_USUA_MODI, NUME_ORDEN,B.USUARIO 
FROM ORDEN A
LEFT OUTER JOIN CLAVESG B ON  A.COD_USUARIO=B.CODIGO AND B.SISTEMA='002' 
WHERE A.ANO_PRESE = '2022'
ORDER BY NUME_ORDEN ASC

COMMIT

DELETE FROM ORDEN_INDICADOR_JM
COMMIT








SELECT DISTINCT COD_USUARIO FROM ORDEN

SELECT * FROM CLAVESG A, ORDEN B WHERE A.CODIGO=B.COD_USUARIO AND B.ANO_PRESE='2022' AND SISTEMA='002'

SELECT * FROM ORDEN_INDICADOR_JM WHERE COMERCIAL IS NULL

------------------------------------------
create or replace TRIGGER AI_ORDEN_INDICADOR_JM 
AFTER INSERT OR UPDATE OR DELETE ON ORDEN 
FOR EACH ROW
DECLARE
K INTEGER;
COD_USER_UP VARCHAR2(6);
USER_UP VARCHAR2(6);
BEGIN

K:= 0;

    IF INSERTING THEN
    --AGREGA A LA TABLA ORDEN_INDICADOR_JM ANO_PRESE,CODI_ADUAN,CODI_CLI,CODI_REGI,EMPRESA,USER_UPDATE, FECHA_UPDATE Y COMERCIAL
        SELECT  COUNT(1) INTO K 
        FROM ORDEN_INDICADOR_JM
        WHERE   EMPRESA = :NEW.EMPRESA AND ANO_PRESE = :NEW.ANO_PRESE AND CODI_ADUAN = :NEW.CODI_ADUAN AND
                TRIM(CODI_REGI) = TRIM(:NEW.CODI_REGI) AND NUME_ORDEN = :NEW.NUME_ORDEN;
                
        IF K < 1 THEN
        
            IF (:NEW.COD_USUARIO IS NOT NULL) THEN
            
                SELECT USUARIO INTO USER_UP
                FROM CLAVESG 
                WHERE CODIGO = :NEW.COD_USUARIO AND SISTEMA = '002' AND ROWNUM = 1;
                
            END IF;
            
            INSERT INTO ORDEN_INDICADOR_JM (ANO_PRESE, CODI_ADUAN, CODI_CLIE, CODI_REGI, COMERCIAL, EMPRESA, FECHA_UPDATE, NUME_ORDEN, USER_UPDATE) 
            VALUES (:NEW.ANO_PRESE,:NEW.CODI_ADUAN,:NEW.CODI_CLIE,:NEW.CODI_REGI,:NEW.COMERCIAL,:NEW.EMPRESA,:NEW.FEC_USUA_MODI,:NEW.NUME_ORDEN, USER_UP);
                
        END IF;
                       
    ELSIF UPDATING THEN
    --ACTUALIZA USER_UPDATE, FECHA_UPDATE Y COMERCIAL
        IF (:NEW.COD_USUARIO IS NOT NULL) THEN
        
            SELECT USUARIO INTO USER_UP
            FROM CLAVESG 
            WHERE CODIGO = :NEW.COD_USUARIO AND SISTEMA = '002' AND ROWNUM = 1;
                      
            UPDATE ORDEN_INDICADOR_JM SET USER_UPDATE = USER_UP, FECHA_UPDATE = :NEW.FEC_USUA_MODI, COMERCIAL = :NEW.COMERCIAL 
            WHERE NUME_ORDEN        = :OLD.NUME_ORDEN AND 
                  ANO_PRESE         = :OLD.ANO_PRESE AND 
                  TRIM(CODI_REGI)   = TRIM(:OLD.CODI_REGI) AND 
                  EMPRESA           = :OLD.EMPRESA AND 
                  TRIM(CODI_ADUAN)  = TRIM(:OLD.CODI_ADUAN);                                   
        END IF;
        
    ELSIF DELETING THEN
    --ELIMINA EL REGISTRO EN LA TABLA ORDEN_INDICADOR_JM 
        DELETE FROM ORDEN_INDICADOR_JM 
        WHERE NUME_ORDEN        = :OLD.NUME_ORDEN AND 
              ANO_PRESE         = :OLD.ANO_PRESE AND 
              TRIM(CODI_REGI)   = TRIM(:OLD.CODI_REGI) AND 
              EMPRESA           = :OLD.EMPRESA AND 
              TRIM(CODI_ADUAN)  = TRIM(:OLD.CODI_ADUAN);
    END IF;
    
    EXCEPTION
          WHEN OTHERS THEN
                UTL_MAIL.send(sender    => 'sig@isco.com.pe',
                recipients => 'jmarquina@isco.com.pe',
                cc         => '',
                bcc        => '',
                subject    => 'Error del disparador AI_ORDEN_INDICADOR_JM',
                message    => sqlerrm,
                mime_type  => 'text/html; charset=iso-8859-1');
  NULL;
        
END;