-------------INDICADORES MAYRA--------------------------------------------------------------------------------------------------------------------------------------

-------------ANALISIS_FACTURAS_VINCULADAS-----------------------------------------------------------------------------------------------------------------------------------------------

SELECT 
        RUC_PROVEEDOR,RAZON_SOCIAL,TIPO_DOCUMENTO,NRO_DOC,FECHA_EMISION,FECHA_SUBIDA_FACTURA,TO_CHAR(FECHA_SUBIDA_FACTURA,'MONTH') MES,ORDEN_VINCULADA,FECHA_VINCULO_ORDEN,USUARIO_VINCULO_ORDEN,FORMA_SUBIDA_FACTURA,
        FEC_SUBIDA,FEC_VINCULACION,
        (TRUNC(FEC_VINCULACION) - TRUNC(FEC_SUBIDA)) DIAS_SIN_FDS,
        F_VALIDAR_REPORT(TRUNC(FEC_VINCULACION) - TRUNC(FEC_SUBIDA)) FILTRO_SIN_FDS,
        (F_DIAS_HABILES_JMV(FEC_SUBIDA,FEC_VINCULACION) - 1) DIFERENCIA_DIAS_UTILES,
        F_VALIDAR_REPORT(F_DIAS_HABILES_JMV(FEC_SUBIDA,FEC_VINCULACION) - 1) INDICADOR,
        CASE WHEN F_VALIDAR_REPORT(TRUNC(FEC_VINCULACION) - TRUNC(FEC_SUBIDA)) = F_VALIDAR_REPORT(F_DIAS_HABILES_JMV(FEC_SUBIDA,FEC_VINCULACION) - 1) THEN 'IGUAL'
             ELSE 'DIFERENTE'
        END VALIDACION
FROM(SELECT  RUC_PROVEEDOR,
        razon_social,
        ruc_adquirente,
        razon_social_adquirente,
        decode(TIPO_DOCUMENTO,'01','FACTURA','07','NOTA CREDITO','08','NOTA DEBITO','NO ESPECIFICADO')TIPO_DOCUMENTO,
        serie || '-'|| numero_documento nro_doc,
        fecha_emision,
        fecha_registro AS FECHA_SUBIDA_FACTURA,        
        nume_orden ORDEN_VINCULADA,
        f_cargar_orden AS FECHA_VINCULO_ORDEN,
        usuario_cargar_orden AS USUARIO_VINCULO_ORDEN,
        DECODE(version_ubl,'2.1','AUTOMATICO','MANUAL') FORMA_SUBIDA_FACTURA,
        CASE WHEN '18:00' > TO_CHAR(fecha_registro,'HH24:MI') THEN TRUNC(fecha_registro)
             ELSE (TRUNC(fecha_registro)+1)
        END FEC_SUBIDA,
        TRUNC(f_cargar_orden) FEC_VINCULACION
        FROM face_facturamz 
        WHERE FECHA_EMISION BETWEEN ('01/01/2022') AND ('31/12/2022') AND TIPO_DOCUMENTO = '01' AND RUC_PROVEEDOR NOT IN ('20100246768','20100457629') AND dar_baja_flag IS NULL AND nume_orden IS NOT NULL AND version_ubl = '2.1')
ORDER BY ORDEN_VINCULADA ASC

----------------CUMPLIMIENTO DEL PLAZO DE OBTENCION DEL PERMISO DE RETIRO EN TA MARITIMO------------------------------

SELECT 
NUME_ORDEN,CODI_ADUAN,CODI_REGI,CODI_TDESP,T_DESPACHO,ANO_PRESE,CLIENTE,CODI_CLIE,FEC_USUA_CREA,FEC_DESPACHO,HORARIO_DESPACHO,FEC_RETIRO,DOC_COMPLETA,FEC_DOC_COMPLETA,COD_TERMINAL,NOMBRE_ALMACEN,TIPO_DIRECCIONAMIENTO,DIA_PROGRAMACION,CANT_FERIADO,
F_PROG_CORREGIDA(1,FEC_DESPACHO) FECHA_PROG_CORREGIDA,
CASE WHEN DIA_FECHA_COM = 'SÁBADO   ' AND TO_CHAR(FEC_DOC_COMPLETA,'HH24:MI') > '12:00'  THEN 'VERDADERO'
     ELSE 'FALSO'
END SABADO_MAS_DE_LAS_12,
F_PROG_CORREGIDA(2,FEC_DOC_COMPLETA) FECHA_DOC_CORREGIDA,
DIA_FECHA_COM,MES_FECHA_COM,
(TRUNC(F_PROG_CORREGIDA(1,FEC_DESPACHO)) - TRUNC(F_PROG_CORREGIDA(2,FEC_DOC_COMPLETA))) DIFERENCIA_DIAS,
CASE WHEN (CODI_ADUAN = '118' AND (NOMBRE_ALMACEN ='DP WORLD CALLAO S.R.L.' OR NOMBRE_ALMACEN ='APM TERMINALS INLAND SERVICES S.A.')) OR CODI_ADUAN <> '118' THEN 'NO APLICA'
     ELSE 'APLICA'
END VERIFICADOR2,
CASE WHEN HORARIO_DESPACHO IS NULL  THEN 'NO HAY FECHA DE PROGRAMACION'
     ELSE 
        CASE WHEN FEC_DOC_COMPLETA IS NULL THEN 'NO HAY FECHA DE DOCUMENTACION'
        ELSE
            CASE WHEN (TRUNC(F_PROG_CORREGIDA(1,FEC_DESPACHO)) - TRUNC(F_PROG_CORREGIDA(2,FEC_DOC_COMPLETA)))>=1 THEN 'SI CUMPLE'
            ELSE 'NO CUMPLE'
            END
        END
END INDICADOR2
FROM(select o.nume_orden,o.codi_aduan,o.codi_regi,o.codi_tdesp,
--o.tipo_despacho,
(SELECT DESCRIPCION  FROM TIPO_ANTICIPADO  where ADUANA = o.codi_aduan  and codigo=o.tipo_despacho) as t_despacho,
o.ano_prese,o.cliente,o.codi_clie,a.fec_usua_crea,a.fec_despacho,
(select des_horario from horario where cod_horario=a.hor_prog)horario_despacho,
--a.hor_prog,
o.fec_retiro,a.doc_completa,a.fec_doc_completa,o.cod_terminal,o.nombre_almacen,
(select TIPO_DIRECCIONAMIENTO FROM SOLICITUD_VB LEFT JOIN  solicitud_vb_orden S ON (S.anio_Solicitud=SOLICITUD_VB.ANIO_SOLICITUD and S.nro_solicitud=SOLICITUD_VB.NRO_SOLICITUD and S.orden_madre=1) WHERE (SOLICITUD_VB.EMPRESA = '001') and (s.ano_prese = a.ano_prese) and (s.nume_orden = o.nume_orden) and rownum=1) tipo_direccionamiento,
TO_CHAR(a.fec_despacho,'DAY') DIA_PROGRAMACION,
F_DIA_FERIADO(a.fec_despacho) CANT_FERIADO,
TO_CHAR(a.fec_doc_completa,'DAY') DIA_FECHA_COM,
TO_CHAR(a.fec_doc_completa,'MONTH') MES_FECHA_COM
from orden O 
inner join prog_despacho_cab A on o.empresa=a.empresa and  o.nume_orden=a.nume_orden and o.codi_regi=a.codi_regi and o.codi_aduan=a.codi_aduan and o.ano_prese=a.ano_prese
where TRUNC(o.fec_retiro) BETWEEN TRUNC(to_date('01/01/2022')) AND TRUNC(to_date('31/12/2022')))
WHERE FEC_DOC_COMPLETA is null
ORDER BY NUME_ORDEN ASC
--WHERE NUME_ORDEN ='008497'


-----------------------------------------------

SELECT NUME_ORDEN,CODI_ADUAN,CODI_REGI,CODI_TDESP,NVL(T_DESPACHO,'SIN T_DESPACHO') AS T_DESPACHO,ANO_PRESE,CLIENTE_RAZON_SOCIAL,FEC_USUA_CREA,
NVL(TO_CHAR(FEC_DESPACHO,'DD/MM/YYYY HH24:MM'),'NO HAY FECHA DE PROGRAMACION') FECHA_DESPACHO,
HORARIO_DESPACHO,
NVL(TO_CHAR(FEC_DESPACHO,'MONTH'),'NO HAY FECHA DE PROGRAMACION') AS MES_FECHA_DESPACHO,
FEC_RETIRO,DOC_COMPLETA,
NVL(TO_CHAR(FEC_DOC_COMPLETA,'DD/MM/YYYY HH24:MM'),'NO HAY FECHA DE DOCUMENTACION') AS FECHA_DOC_COMPLETA,
NVL(TO_CHAR(FEC_DOC_COMPLETA,'MONTH'),'NO HAY FECHA DE DOCUMENTACION') AS MES_DOC_COMPLETA,
COD_TERMINAL,NOMBRE_ALMACEN,TIPO_DIRECCIONAMIENTO,
NVL(DIA_PROGRAMACION,'NO HAY FECHA DE PROGRAMACION') AS DIA_PROGRAMAC,
CANT_FERIADO,
CASE WHEN FEC_DESPACHO IS NOT NULL THEN TO_CHAR(F_PROG_CORREGIDA(1,FEC_DESPACHO),'DD/MM/YYYY')
     ELSE 'NO HAY FECHA DE PROGRAMACION'
END FECHA_PROG_CORREGIDA,
CASE WHEN DIA_FECHA_COM = 'SÁBADO   ' AND TO_CHAR(FEC_DOC_COMPLETA,'HH24:MI') > '12:00'  THEN 'VERDADERO'
     ELSE 'FALSO'
END SABADO_MAS_DE_LAS_12,
CASE WHEN FEC_DOC_COMPLETA IS NOT NULL THEN TO_CHAR(F_PROG_CORREGIDA(2,FEC_DOC_COMPLETA),'DD/MM/YYYY') 
     ELSE 'NO HAY FECHA DE DOCUMENTACION'
     END FECHA_DOC_CORREGIDA,
CASE WHEN FEC_DOC_COMPLETA IS NOT NULL THEN DIA_FECHA_COM
     ELSE 'NO HAY FECHA DE DOCUMENTACION'
     END DIA_FECHA_DOC_COM,
CASE WHEN FEC_DOC_COMPLETA IS NOT NULL THEN MES_FECHA_COM
     ELSE 'NO HAY FECHA DE DOCUMENTACION'
     END MES_FECHA_DOC_COM,
NVL(TRUNC(F_PROG_CORREGIDA(1,FEC_DESPACHO)) - TRUNC(F_PROG_CORREGIDA(2,FEC_DOC_COMPLETA)),0) DIFERENCIA_DIAS,
CASE WHEN (CODI_ADUAN = '118' AND (NOMBRE_ALMACEN ='DP WORLD CALLAO S.R.L.' OR NOMBRE_ALMACEN ='APM TERMINALS INLAND SERVICES S.A.')) OR CODI_ADUAN <> '118' THEN 'NO APLICA'
     ELSE 'APLICA'
END VERIFICADOR2,
CASE WHEN HORARIO_DESPACHO IS NULL  THEN 'NO HAY FECHA DE PROGRAMACION'
     ELSE 
        CASE WHEN FEC_DOC_COMPLETA IS NULL THEN 'NO HAY FECHA DE DOCUMENTACION'
        ELSE
            CASE WHEN (TRUNC(F_PROG_CORREGIDA(1,FEC_DESPACHO)) - TRUNC(F_PROG_CORREGIDA(2,FEC_DOC_COMPLETA)))>=1 THEN 'SI CUMPLE'
            ELSE 'NO CUMPLE'
            END
        END
END INDICADOR2
FROM(SELECT O.NUME_ORDEN,O.CODI_ADUAN,O.CODI_REGI,O.CODI_tdesp,
    (SELECT DESCRIPCION  FROM TIPO_ANTICIPADO WHERE ADUANA = O.CODI_ADUAN  AND CODIGO = O.TIPO_DESPACHO) AS T_DESPACHO,
    O.ANO_PRESE,
    (SELECT RASON_SOCIAL FROM CLIENTES WHERE CODIGOANT = O.CODI_CLIE AND ROWNUM = 1) CLIENTE_RAZON_SOCIAL,
    A.FEC_USUA_CREA,A.FEC_DESPACHO,
    (SELECT DES_HORARIO FROM HORARIO WHERE COD_HORARIO = A.hor_prog) HORARIO_DESPACHO,
    O.FEC_RETIRO,A.DOC_COMPLETA,
    A.FEC_DOC_COMPLETA,
    O.COD_TERMINAL,O.NOMBRE_ALMACEN,
    (SELECT TIPO_DIRECCIONAMIENTO FROM SOLICITUD_VB LEFT JOIN SOLICITUD_VB_ORDEN S ON (S.ANIO_SOLICITUD = SOLICITUD_VB.ANIO_SOLICITUD AND S.NRO_SOLICITUD = SOLICITUD_VB.NRO_SOLICITUD AND S.ORDEN_MADRE = 1) WHERE (SOLICITUD_VB.EMPRESA = '001') AND (S.ANO_PRESE = A.ANO_PRESE) AND (S.NUME_ORDEN = O.NUME_ORDEN) AND ROWNUM = 1) tipo_direccionamiento,
    TO_CHAR(A.FEC_DESPACHO,'DAY') DIA_PROGRAMACION,
    F_DIA_FERIADO(A.FEC_DESPACHO) CANT_FERIADO,
    TO_CHAR(A.FEC_DOC_COMPLETA,'DAY') DIA_FECHA_COM,
    TO_CHAR(A.FEC_DOC_COMPLETA,'MONTH') MES_FECHA_COM
    FROM ORDEN O 
    INNER JOIN PROG_DESPACHO_CAB A ON (O.EMPRESA = A.EMPRESA AND O.NUME_ORDEN = A.NUME_ORDEN AND O.CODI_REGI = A.CODI_REGI AND O.CODI_ADUAN = A.CODI_ADUAN AND O.ANO_PRESE = A.ANO_PRESE)
    WHERE TRUNC(O.FEC_RETIRO) BETWEEN TRUNC(to_date('01/01/2022')) AND TRUNC(to_date('31/12/2022')))
--WHERE FEC_DOC_COMPLETA IS NULL
ORDER BY NUME_ORDEN ASC
--WHERE NUME_ORDEN ='008497'

-----------------------------------------------------------------------------------------------------------


SELECT NUME_ORDEN,CODI_ADUAN,CODI_REGI,CODI_TDESP,NVL(T_DESPACHO,'SIN T_DESPACHO') AS T_DESPACHO,ANO_PRESE,CLIENTE_RAZON_SOCIAL,FEC_USUA_CREA,
NVL(TO_CHAR(FEC_DESPACHO,'DD/MM/YYYY HH24:MM'),'NO HAY FECHA DE PROGRAMACION') FECHA_DESPACHO,
HORARIO_DESPACHO,
NVL(TO_CHAR(FEC_DESPACHO,'MONTH'),'NO HAY FECHA DE PROGRAMACION') AS MES_FECHA_DESPACHO,
FEC_RETIRO,DOC_COMPLETA,
NVL(TO_CHAR(FEC_DOC_COMPLETA,'DD/MM/YYYY HH24:MM'),'NO HAY FECHA DE DOCUMENTACION') AS FECHA_DOC_COMPLETA,
NVL(TO_CHAR(FEC_DOC_COMPLETA,'MONTH'),'NO HAY FECHA DE DOCUMENTACION') AS MES_DOC_COMPLETA,
COD_TERMINAL,NOMBRE_ALMACEN,TIPO_DIRECCIONAMIENTO,
DIA_PROGRAMACION AS DIA_PROGRAMAC,
CANT_FERIADO,
CASE WHEN FEC_DESPACHO IS NOT NULL THEN TO_CHAR(F_PROG_CORREGIDA(1,FEC_DESPACHO),'DD/MM/YYYY')
     ELSE 'NO HAY FECHA DE PROGRAMACION'
END FECHA_PROG_CORREGIDA,
CASE WHEN DIA_FECHA_COM = 'SÁBADO   ' AND TO_CHAR(FEC_DOC_COMPLETA,'HH24:MI') > '12:00'  THEN 'VERDADERO'
     ELSE 'FALSO'
END SABADO_MAS_DE_LAS_12,
CASE WHEN FEC_DOC_COMPLETA IS NOT NULL THEN TO_CHAR(F_PROG_CORREGIDA(2,FEC_DOC_COMPLETA),'DD/MM/YYYY') 
     ELSE 'NO HAY FECHA DE DOCUMENTACION'
     END FECHA_DOC_CORREGIDA,
CASE WHEN FEC_DOC_COMPLETA IS NOT NULL THEN DIA_FECHA_COM
     ELSE 'NO HAY FECHA DE DOCUMENTACION'
     END DIA_FECHA_DOC_COM,
CASE WHEN FEC_DOC_COMPLETA IS NOT NULL THEN MES_FECHA_COM
     ELSE 'NO HAY FECHA DE DOCUMENTACION'
     END MES_FECHA_DOC_COM,
NVL(TRUNC(F_PROG_CORREGIDA(1,FEC_DESPACHO)) - TRUNC(F_PROG_CORREGIDA(2,FEC_DOC_COMPLETA)),0) DIFERENCIA_DIAS,
CASE WHEN (CODI_ADUAN = '118' AND (NOMBRE_ALMACEN ='DP WORLD CALLAO S.R.L.' OR NOMBRE_ALMACEN ='APM TERMINALS INLAND SERVICES S.A.')) OR CODI_ADUAN <> '118' THEN 'NO APLICA'
     ELSE 'APLICA'
END VERIFICADOR2,
CASE WHEN HORARIO_DESPACHO IS NULL  THEN 'NO HAY FECHA DE PROGRAMACION'
     ELSE 
        CASE WHEN FEC_DOC_COMPLETA IS NULL THEN 'NO HAY FECHA DE DOCUMENTACION'
        ELSE
            CASE WHEN (TRUNC(F_PROG_CORREGIDA(1,FEC_DESPACHO)) - TRUNC(F_PROG_CORREGIDA(2,FEC_DOC_COMPLETA)))>=1 THEN 'SI CUMPLE'
            ELSE 'NO CUMPLE'
            END
        END
END INDICADOR2
FROM(SELECT O.NUME_ORDEN,O.CODI_ADUAN,O.CODI_REGI,O.CODI_tdesp,
    (SELECT DESCRIPCION  FROM TIPO_ANTICIPADO WHERE ADUANA = O.CODI_ADUAN  AND CODIGO = O.TIPO_DESPACHO) AS T_DESPACHO,
    O.ANO_PRESE,
    (SELECT RASON_SOCIAL FROM CLIENTES WHERE CODIGOANT = O.CODI_CLIE AND ROWNUM = 1) CLIENTE_RAZON_SOCIAL,
    A.FEC_USUA_CREA,A.FEC_DESPACHO,
    (SELECT DES_HORARIO FROM HORARIO WHERE COD_HORARIO = A.hor_prog) HORARIO_DESPACHO,
    O.FEC_RETIRO,A.DOC_COMPLETA,
    A.FEC_DOC_COMPLETA,
    O.COD_TERMINAL,O.NOMBRE_ALMACEN,
    (SELECT TIPO_DIRECCIONAMIENTO FROM SOLICITUD_VB LEFT JOIN SOLICITUD_VB_ORDEN S ON (S.ANIO_SOLICITUD = SOLICITUD_VB.ANIO_SOLICITUD AND S.NRO_SOLICITUD = SOLICITUD_VB.NRO_SOLICITUD AND S.ORDEN_MADRE = 1) WHERE (SOLICITUD_VB.EMPRESA = '001') AND (S.ANO_PRESE = A.ANO_PRESE) AND (S.NUME_ORDEN = O.NUME_ORDEN) AND ROWNUM = 1) tipo_direccionamiento,
    CASE WHEN A.FEC_DOC_COMPLETA IS NOT NULL THEN  TO_CHAR(A.FEC_DESPACHO,'DAY')
         ELSE 'NO HAY FECHA DE PROGRAMACION'
     END DIA_PROGRAMACION,
    F_DIA_FERIADO(A.FEC_DESPACHO) CANT_FERIADO,
    TO_CHAR(A.FEC_DOC_COMPLETA,'DAY') DIA_FECHA_COM,
    TO_CHAR(A.FEC_DOC_COMPLETA,'MONTH') MES_FECHA_COM
    FROM ORDEN O 
    INNER JOIN PROG_DESPACHO_CAB A ON (O.EMPRESA = A.EMPRESA AND O.NUME_ORDEN = A.NUME_ORDEN AND O.CODI_REGI = A.CODI_REGI AND O.CODI_ADUAN = A.CODI_ADUAN AND O.ANO_PRESE = A.ANO_PRESE)
    WHERE TRUNC(O.FEC_RETIRO) BETWEEN TRUNC(TO_DATE('01/01/2022')) AND TRUNC(TO_DATE('31/12/2022')))
ORDER BY NUME_ORDEN ASC
--WHERE NUME_ORDEN ='008497'


------------------------------

SELECT NUME_ORDEN,CODI_ADUAN,CODI_REGI,CODI_TDESP,NVL(T_DESPACHO,'SIN T_DESPACHO') AS T_DESPACHO,ANO_PRESE,CLIENTE_RAZON_SOCIAL,FEC_USUA_CREA,
NVL(TO_CHAR(FEC_DESPACHO,'DD/MM/YYYY HH24:MM:SS'),'NO HAY FECHA DE PROGRAMACION') FECHA_DESPACHO,
HORARIO_DESPACHO,
NVL(TO_CHAR(FEC_DESPACHO,'MONTH'),'NO HAY FECHA DE PROGRAMACION') AS MES_FECHA_DESPACHO,
FEC_RETIRO,DOC_COMPLETA,
NVL(TO_CHAR(FEC_DOC_COMPLETA,'DD/MM/YYYY HH24:MM:SS'),'NO HAY FECHA DE DOCUMENTACION') AS FECHA_DOC_COMPLETA,
NVL(TO_CHAR(FEC_DOC_COMPLETA,'MONTH'),'NO HAY FECHA DE DOCUMENTACION') AS MES_DOC_COMPLETA,
COD_TERMINAL,NOMBRE_ALMACEN,TIPO_DIRECCIONAMIENTO,
DIA_PROGRAMACION AS DIA_PROGRAMAC,
CANT_FERIADO,
CASE WHEN FEC_DESPACHO IS NOT NULL THEN TO_CHAR(F_PROG_CORREGIDA(1,FEC_DESPACHO),'DD/MM/YYYY')
     ELSE 'NO HAY FECHA DE PROGRAMACION'
END FECHA_PROG_CORREGIDA,
CASE WHEN DIA_FECHA_COM = 'SÁBADO   ' AND TO_CHAR(FEC_DOC_COMPLETA,'HH24:MI:SS') > '12:00:00'  THEN 'VERDADERO'
     ELSE 'FALSO'
END SABADO_MAS_DE_LAS_12,
CASE WHEN FEC_DOC_COMPLETA IS NOT NULL THEN TO_CHAR(F_PROG_CORREGIDA(2,FEC_DOC_COMPLETA),'DD/MM/YYYY') 
     ELSE 'NO HAY FECHA DE DOCUMENTACION'
END FECHA_DOC_CORREGIDA,
CASE WHEN FEC_DOC_COMPLETA IS NOT NULL THEN DIA_FECHA_COM
     ELSE 'NO HAY FECHA DE DOCUMENTACION'
END DIA_FECHA_DOC_COM,
CASE WHEN FEC_DOC_COMPLETA IS NOT NULL THEN MES_FECHA_COM
     ELSE 'NO HAY FECHA DE DOCUMENTACION'
END MES_FECHA_DOC_COM,
CASE WHEN FEC_DOC_COMPLETA IS NOT NULL THEN MES_FECHA_COM
     ELSE TO_CHAR(FEC_RETIRO,'MONTH')
END MES_FINAL,
CASE WHEN TRUNC(F_PROG_CORREGIDA(1,FEC_DESPACHO)) > TRUNC(F_PROG_CORREGIDA(2,FEC_DOC_COMPLETA)) THEN TRUNC(F_PROG_CORREGIDA(1,FEC_DESPACHO)) - TRUNC(F_PROG_CORREGIDA(2,FEC_DOC_COMPLETA))
     ELSE 0
END DIFERENCIA_DIAS,
CASE WHEN (CODI_ADUAN = '118' AND (NOMBRE_ALMACEN ='DP WORLD CALLAO S.R.L.' OR NOMBRE_ALMACEN ='APM TERMINALS CALLAO S.A.')) OR CODI_ADUAN <> '118' THEN 'NO APLICA'
     ELSE 'APLICA'
END VERIFICADOR2,
CASE WHEN FEC_DESPACHO IS NULL  THEN 'NO HAY FECHA DE PROGRAMACION'
     ELSE 
        CASE WHEN FEC_DOC_COMPLETA IS NULL THEN 'NO HAY FECHA DE DOCUMENTACION'
        ELSE
            CASE WHEN (TRUNC(F_PROG_CORREGIDA(1,FEC_DESPACHO)) - TRUNC(F_PROG_CORREGIDA(2,FEC_DOC_COMPLETA)))>=1 THEN 'SI CUMPLE'
            ELSE 'NO CUMPLE'
        END
     END
END INDICADOR2,
F_INDICADOR2_MAYRA_JM(FEC_DESPACHO,FEC_DOC_COMPLETA) AS INDICADOR3
FROM(SELECT O.NUME_ORDEN,O.CODI_ADUAN,O.CODI_REGI,O.CODI_TDESP,
    (SELECT DESCRIPCION  FROM TIPO_ANTICIPADO WHERE ADUANA = O.CODI_ADUAN  AND CODIGO = O.TIPO_DESPACHO) AS T_DESPACHO,
    O.ANO_PRESE,
    (SELECT RASON_SOCIAL FROM CLIENTES WHERE CODIGOANT = O.CODI_CLIE AND ROWNUM = 1) CLIENTE_RAZON_SOCIAL,
    A.FEC_USUA_CREA,A.FEC_DESPACHO,
    (SELECT DES_HORARIO FROM HORARIO WHERE COD_HORARIO = A.hor_prog) HORARIO_DESPACHO,
    O.FEC_RETIRO,A.DOC_COMPLETA,
    A.FEC_DOC_COMPLETA,
    O.COD_TERMINAL,O.NOMBRE_ALMACEN,
    (SELECT TIPO_DIRECCIONAMIENTO FROM SOLICITUD_VB LEFT JOIN SOLICITUD_VB_ORDEN S ON (S.ANIO_SOLICITUD = SOLICITUD_VB.ANIO_SOLICITUD AND S.NRO_SOLICITUD = SOLICITUD_VB.NRO_SOLICITUD AND S.ORDEN_MADRE = 1) WHERE (SOLICITUD_VB.EMPRESA = '001') AND (S.ANO_PRESE = A.ANO_PRESE) AND (S.NUME_ORDEN = O.NUME_ORDEN) AND ROWNUM = 1) TIPO_DIRECCIONAMIENTO,
    CASE WHEN A.FEC_DOC_COMPLETA IS NOT NULL THEN  TO_CHAR(A.FEC_DESPACHO,'DAY')
         ELSE 'NO HAY FECHA DE PROGRAMACION'
     END DIA_PROGRAMACION,
    F_DIA_FERIADO(A.FEC_DESPACHO) CANT_FERIADO,
    TO_CHAR(A.FEC_DOC_COMPLETA,'DAY') DIA_FECHA_COM,
    TO_CHAR(A.FEC_DOC_COMPLETA,'MONTH') MES_FECHA_COM
    FROM ORDEN O 
    INNER JOIN PROG_DESPACHO_CAB A ON (O.EMPRESA = A.EMPRESA AND O.NUME_ORDEN = A.NUME_ORDEN AND O.CODI_REGI = A.CODI_REGI AND O.CODI_ADUAN = A.CODI_ADUAN AND O.ANO_PRESE = A.ANO_PRESE)
    WHERE TRUNC(O.FEC_RETIRO) BETWEEN TRUNC(TO_DATE('01/01/2022')) AND TRUNC(TO_DATE('31/12/2022')))
WHERE NUME_ORDEN = '016762'
ORDER BY NUME_ORDEN ASC;
